# Copyright 2026 50Hertz Transmission GmbH and Elia Transmission Belgium
#
# This Source Code Form is subject to the terms of the Mozilla Public License, v. 2.0.
# If a copy of the MPL was not distributed with this file,
# you can obtain one at https://mozilla.org/MPL/2.0/.
# Mozilla Public License, version 2.0

trigger:
  tags:
    include:
      - "v*" # Trigger on version tags

jobs:
  - job: PublishPackages
    displayName: Publish Packages
    pool:
      vmImage: ubuntu-latest

    strategy:
      matrix:
        interfaces:
          packageName: interfaces
        grid_helpers:
          packageName: grid_helpers
        contingency_analysis:
          packageName: contingency_analysis
        dc_solver:
          packageName: dc_solver
        importer:
          packageName: importer
        topology_optimizer:
          packageName: topology_optimizer

    steps:
      - checkout: self
        clean: true

      - task: UsePythonVersion@0
        displayName: Configure Python version
        inputs:
          versionSpec: "3.11"

      - task: Bash@3
        displayName: Install uv
        inputs:
          targetType: inline
          script: |
            pipx install uv

      - script: |
          uv build
          uv publish --index MCCS --username __token__ --password $SYSTEM_ACCESS_TOKEN
        displayName: Publish $(packageName) package
        workingDirectory: packages/$(packageName)_pkg
        env:
          SYSTEM_ACCESS_TOKEN: $(System.AccessToken)
