# Copyright 2026 50Hertz Transmission GmbH and Elia Transmission Belgium SA/NV
#
# This Source Code Form is subject to the terms of the Mozilla Public License, v. 2.0.
# If a copy of the MPL was not distributed with this file,
# you can obtain one at https://mozilla.org/MPL/2.0/.
# Mozilla Public License, version 2.0

name: "Configure Git Profile"
description: "Configures git user name and email for committing changes in GitHub Actions workflows"

inputs:
  email:
    description: "Git user email to configure"
    required: false
    default: "ToOp@eliagroup.eu"
  username:
    description: "Git user name to configure"
    required: false
    default: "ToOp Build Service"

runs:
  using: "composite"
  steps:
    - name: Configure git profile
      run: |
        git config user.name "${{ inputs.username }}"
        git config user.email "${{ inputs.email }}"
