"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""
import builtins
import collections.abc
import google.protobuf.descriptor
import google.protobuf.internal.containers
import google.protobuf.message
import sys

if sys.version_info >= (3, 8):
    import typing as typing_extensions
else:
    import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

class BaseFilter(google.protobuf.message.Message):
    """=====================================================
    FILTER DEFINITIONS
    =====================================================

    Base class for filters
    """

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    FILTER_TYPE_FIELD_NUMBER: builtins.int
    filter_type: builtins.str
    def __init__(
        self,
        *,
        filter_type: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["filter_type", b"filter_type"]) -> None: ...

global___BaseFilter = BaseFilter

class WorstContingencyBranchFilter(google.protobuf.message.Message):
    """Reduces branch results to only the worst N-1 contingency per branch/timestep"""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    RETURN_BASECASE_FIELD_NUMBER: builtins.int
    FILTER_TYPE_FIELD_NUMBER: builtins.int
    return_basecase: builtins.bool
    """Whether to return the basecase as well"""
    filter_type: builtins.str
    """Identifier: "worst_contingency" """
    def __init__(
        self,
        *,
        return_basecase: builtins.bool = ...,
        filter_type: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["filter_type", b"filter_type", "return_basecase", b"return_basecase"]) -> None: ...

global___WorstContingencyBranchFilter = WorstContingencyBranchFilter

class VoltageBandFilter(google.protobuf.message.Message):
    """Reduces node results to only those outside a specified voltage band"""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    RETURN_BASECASE_FIELD_NUMBER: builtins.int
    V_MIN_FIELD_NUMBER: builtins.int
    V_MAX_FIELD_NUMBER: builtins.int
    FILTER_TYPE_FIELD_NUMBER: builtins.int
    return_basecase: builtins.bool
    """Whether to always return the basecase"""
    v_min: builtins.float
    """Minimum voltage (p.u.)"""
    v_max: builtins.float
    """Maximum voltage (p.u.)"""
    filter_type: builtins.str
    """Identifier: "voltage_band" """
    def __init__(
        self,
        *,
        return_basecase: builtins.bool = ...,
        v_min: builtins.float = ...,
        v_max: builtins.float = ...,
        filter_type: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["filter_type", b"filter_type", "return_basecase", b"return_basecase", "v_max", b"v_max", "v_min", b"v_min"]) -> None: ...

global___VoltageBandFilter = VoltageBandFilter

class PercentCutoffBranchFilter(google.protobuf.message.Message):
    """Returns only branches above a loading threshold"""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    LOADING_THRESHOLD_FIELD_NUMBER: builtins.int
    FILTER_TYPE_FIELD_NUMBER: builtins.int
    loading_threshold: builtins.float
    """Loading threshold in percent"""
    filter_type: builtins.str
    """Identifier: "percent_cutoff" """
    def __init__(
        self,
        *,
        loading_threshold: builtins.float = ...,
        filter_type: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["filter_type", b"filter_type", "loading_threshold", b"loading_threshold"]) -> None: ...

global___PercentCutoffBranchFilter = PercentCutoffBranchFilter

class BaseGrid(google.protobuf.message.Message):
    """=====================================================
    GRID DEFINITIONS
    =====================================================

    Base class for grids
    """

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    GRID_TYPE_FIELD_NUMBER: builtins.int
    N_1_DEFINITION_FIELD_NUMBER: builtins.int
    grid_type: builtins.str
    """Discriminator for grid subtype"""
    n_1_definition: builtins.str
    """Optional N-1 definition (serialized)"""
    def __init__(
        self,
        *,
        grid_type: builtins.str = ...,
        n_1_definition: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["grid_type", b"grid_type", "n_1_definition", b"n_1_definition"]) -> None: ...

global___BaseGrid = BaseGrid

class CGMESGrid(google.protobuf.message.Message):
    """CGMES grid"""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    GRID_FILES_FIELD_NUMBER: builtins.int
    N_1_DEFINITION_FIELD_NUMBER: builtins.int
    GRID_TYPE_FIELD_NUMBER: builtins.int
    @property
    def grid_files(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.str]:
        """List of .tp/.ssh files"""
    n_1_definition: builtins.str
    grid_type: builtins.str
    """"cgmes" """
    def __init__(
        self,
        *,
        grid_files: collections.abc.Iterable[builtins.str] | None = ...,
        n_1_definition: builtins.str = ...,
        grid_type: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["grid_files", b"grid_files", "grid_type", b"grid_type", "n_1_definition", b"n_1_definition"]) -> None: ...

global___CGMESGrid = CGMESGrid

class UCTEGrid(google.protobuf.message.Message):
    """UCTE grid"""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    GRID_FILES_FIELD_NUMBER: builtins.int
    N_1_DEFINITION_FIELD_NUMBER: builtins.int
    GRID_TYPE_FIELD_NUMBER: builtins.int
    @property
    def grid_files(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.str]:
        """List of .ucte files"""
    n_1_definition: builtins.str
    grid_type: builtins.str
    """"ucte" """
    def __init__(
        self,
        *,
        grid_files: collections.abc.Iterable[builtins.str] | None = ...,
        n_1_definition: builtins.str = ...,
        grid_type: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["grid_files", b"grid_files", "grid_type", b"grid_type", "n_1_definition", b"n_1_definition"]) -> None: ...

global___UCTEGrid = UCTEGrid

class PowsyblGrid(google.protobuf.message.Message):
    """Powsybl grid"""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    GRID_FILES_FIELD_NUMBER: builtins.int
    N_1_DEFINITION_FIELD_NUMBER: builtins.int
    GRID_TYPE_FIELD_NUMBER: builtins.int
    @property
    def grid_files(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.str]:
        """List of .xiidm files"""
    n_1_definition: builtins.str
    grid_type: builtins.str
    """"powsybl" """
    def __init__(
        self,
        *,
        grid_files: collections.abc.Iterable[builtins.str] | None = ...,
        n_1_definition: builtins.str = ...,
        grid_type: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["grid_files", b"grid_files", "grid_type", b"grid_type", "n_1_definition", b"n_1_definition"]) -> None: ...

global___PowsyblGrid = PowsyblGrid

class PandapowerGrid(google.protobuf.message.Message):
    """Pandapower grid"""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    GRID_FILES_FIELD_NUMBER: builtins.int
    N_1_DEFINITION_FIELD_NUMBER: builtins.int
    GRID_TYPE_FIELD_NUMBER: builtins.int
    @property
    def grid_files(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.str]:
        """List of pandapower .json files"""
    n_1_definition: builtins.str
    grid_type: builtins.str
    """"pandapower" """
    def __init__(
        self,
        *,
        grid_files: collections.abc.Iterable[builtins.str] | None = ...,
        n_1_definition: builtins.str = ...,
        grid_type: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["grid_files", b"grid_files", "grid_type", b"grid_type", "n_1_definition", b"n_1_definition"]) -> None: ...

global___PandapowerGrid = PandapowerGrid

class InjectionAddition(google.protobuf.message.Message):
    """=====================================================
    JOB DEFINITIONS
    =====================================================

    A single addition of an injection at a node
    """

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    NODE_FIELD_NUMBER: builtins.int
    P_MW_FIELD_NUMBER: builtins.int
    Q_MW_FIELD_NUMBER: builtins.int
    TIMESTEP_SUBSELECTION_FIELD_NUMBER: builtins.int
    node: builtins.str
    """Node where injection is added (GridElement reference)"""
    p_mw: builtins.float
    """Active power in MW"""
    q_mw: builtins.float
    """Reactive power in MW"""
    @property
    def timestep_subselection(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.int]:
        """Timesteps where addition applies"""
    def __init__(
        self,
        *,
        node: builtins.str = ...,
        p_mw: builtins.float = ...,
        q_mw: builtins.float = ...,
        timestep_subselection: collections.abc.Iterable[builtins.int] | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["node", b"node", "p_mw", b"p_mw", "q_mw", b"q_mw", "timestep_subselection", b"timestep_subselection"]) -> None: ...

global___InjectionAddition = InjectionAddition

class Job(google.protobuf.message.Message):
    """Base job definition"""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    ID_FIELD_NUMBER: builtins.int
    WORST_CONTINGENCY_FIELD_NUMBER: builtins.int
    PERCENT_CUTOFF_FIELD_NUMBER: builtins.int
    NODE_FILTER_FIELD_NUMBER: builtins.int
    JOB_TYPE_FIELD_NUMBER: builtins.int
    TIMESTEP_SUBSELECTION_FIELD_NUMBER: builtins.int
    id: builtins.str
    """Unique job identifier"""
    @property
    def worst_contingency(self) -> global___WorstContingencyBranchFilter: ...
    @property
    def percent_cutoff(self) -> global___PercentCutoffBranchFilter: ...
    @property
    def node_filter(self) -> global___VoltageBandFilter:
        """Optional node results filter"""
    job_type: builtins.str
    """Job discriminator"""
    @property
    def timestep_subselection(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.int]:
        """Timesteps to compute"""
    def __init__(
        self,
        *,
        id: builtins.str = ...,
        worst_contingency: global___WorstContingencyBranchFilter | None = ...,
        percent_cutoff: global___PercentCutoffBranchFilter | None = ...,
        node_filter: global___VoltageBandFilter | None = ...,
        job_type: builtins.str = ...,
        timestep_subselection: collections.abc.Iterable[builtins.int] | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["branch_filter", b"branch_filter", "node_filter", b"node_filter", "percent_cutoff", b"percent_cutoff", "worst_contingency", b"worst_contingency"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["branch_filter", b"branch_filter", "id", b"id", "job_type", b"job_type", "node_filter", b"node_filter", "percent_cutoff", b"percent_cutoff", "timestep_subselection", b"timestep_subselection", "worst_contingency", b"worst_contingency"]) -> None: ...
    def WhichOneof(self, oneof_group: typing_extensions.Literal["branch_filter", b"branch_filter"]) -> typing_extensions.Literal["worst_contingency", "percent_cutoff"] | None: ...

global___Job = Job

class JobWithSwitchingStrategy(google.protobuf.message.Message):
    """Job with switching strategy"""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    BASE_FIELD_NUMBER: builtins.int
    STRATEGY_FIELD_NUMBER: builtins.int
    @property
    def base(self) -> global___Job:
        """Base job parameters"""
    strategy: builtins.str
    """Switching strategy (serialized)"""
    def __init__(
        self,
        *,
        base: global___Job | None = ...,
        strategy: builtins.str = ...,
    ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["base", b"base"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["base", b"base", "strategy", b"strategy"]) -> None: ...

global___JobWithSwitchingStrategy = JobWithSwitchingStrategy

class JobWithCGMESChanges(google.protobuf.message.Message):
    """Job with CGMES changes"""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    BASE_FIELD_NUMBER: builtins.int
    TP_FILES_FIELD_NUMBER: builtins.int
    SSH_FILES_FIELD_NUMBER: builtins.int
    @property
    def base(self) -> global___Job:
        """Base job parameters"""
    @property
    def tp_files(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.str]:
        """Topology change files (.tp)"""
    @property
    def ssh_files(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.str]:
        """State/injection change files (.ssh)"""
    def __init__(
        self,
        *,
        base: global___Job | None = ...,
        tp_files: collections.abc.Iterable[builtins.str] | None = ...,
        ssh_files: collections.abc.Iterable[builtins.str] | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["base", b"base"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["base", b"base", "ssh_files", b"ssh_files", "tp_files", b"tp_files"]) -> None: ...

global___JobWithCGMESChanges = JobWithCGMESChanges

class JobWithInjectionAdditions(google.protobuf.message.Message):
    """Job adding injections"""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    BASE_FIELD_NUMBER: builtins.int
    ADDITIONS_FIELD_NUMBER: builtins.int
    @property
    def base(self) -> global___Job:
        """Base job parameters"""
    @property
    def additions(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___InjectionAddition]:
        """Injections to apply"""
    def __init__(
        self,
        *,
        base: global___Job | None = ...,
        additions: collections.abc.Iterable[global___InjectionAddition] | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["base", b"base"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["additions", b"additions", "base", b"base"]) -> None: ...

global___JobWithInjectionAdditions = JobWithInjectionAdditions

class StartCalculationCommand(google.protobuf.message.Message):
    """=====================================================
    COMMAND DEFINITIONS
    =====================================================

    Command to start a list of loadflow jobs
    """

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    LOADFLOW_ID_FIELD_NUMBER: builtins.int
    POWSYBL_GRID_FIELD_NUMBER: builtins.int
    PANDAPOWER_GRID_FIELD_NUMBER: builtins.int
    UCTE_GRID_FIELD_NUMBER: builtins.int
    CGMES_GRID_FIELD_NUMBER: builtins.int
    METHOD_FIELD_NUMBER: builtins.int
    JOBS_FIELD_NUMBER: builtins.int
    loadflow_id: builtins.str
    """Unique identifier for this loadflow run"""
    @property
    def powsybl_grid(self) -> global___PowsyblGrid: ...
    @property
    def pandapower_grid(self) -> global___PandapowerGrid: ...
    @property
    def ucte_grid(self) -> global___UCTEGrid: ...
    @property
    def cgmes_grid(self) -> global___CGMESGrid: ...
    method: builtins.str
    """AC or DC loadflow method"""
    @property
    def jobs(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___Job]:
        """Jobs to execute"""
    def __init__(
        self,
        *,
        loadflow_id: builtins.str = ...,
        powsybl_grid: global___PowsyblGrid | None = ...,
        pandapower_grid: global___PandapowerGrid | None = ...,
        ucte_grid: global___UCTEGrid | None = ...,
        cgmes_grid: global___CGMESGrid | None = ...,
        method: builtins.str = ...,
        jobs: collections.abc.Iterable[global___Job] | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["cgmes_grid", b"cgmes_grid", "grid_data", b"grid_data", "pandapower_grid", b"pandapower_grid", "powsybl_grid", b"powsybl_grid", "ucte_grid", b"ucte_grid"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["cgmes_grid", b"cgmes_grid", "grid_data", b"grid_data", "jobs", b"jobs", "loadflow_id", b"loadflow_id", "method", b"method", "pandapower_grid", b"pandapower_grid", "powsybl_grid", b"powsybl_grid", "ucte_grid", b"ucte_grid"]) -> None: ...
    def WhichOneof(self, oneof_group: typing_extensions.Literal["grid_data", b"grid_data"]) -> typing_extensions.Literal["powsybl_grid", "pandapower_grid", "ucte_grid", "cgmes_grid"] | None: ...

global___StartCalculationCommand = StartCalculationCommand

class ShutdownCommand(google.protobuf.message.Message):
    """Command to shut down the worker"""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    EXIT_CODE_FIELD_NUMBER: builtins.int
    exit_code: builtins.int
    """Exit code (default: 0)"""
    def __init__(
        self,
        *,
        exit_code: builtins.int = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["exit_code", b"exit_code"]) -> None: ...

global___ShutdownCommand = ShutdownCommand

class LoadflowServiceCommand(google.protobuf.message.Message):
    """Wrapper for service communication"""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    START_CALCULATION_FIELD_NUMBER: builtins.int
    SHUTDOWN_FIELD_NUMBER: builtins.int
    TIMESTAMP_FIELD_NUMBER: builtins.int
    UUID_FIELD_NUMBER: builtins.int
    @property
    def start_calculation(self) -> global___StartCalculationCommand: ...
    @property
    def shutdown(self) -> global___ShutdownCommand: ...
    timestamp: builtins.str
    """Timestamp of when the command was sent"""
    uuid: builtins.str
    """Unique message identifier"""
    def __init__(
        self,
        *,
        start_calculation: global___StartCalculationCommand | None = ...,
        shutdown: global___ShutdownCommand | None = ...,
        timestamp: builtins.str = ...,
        uuid: builtins.str = ...,
    ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["command", b"command", "shutdown", b"shutdown", "start_calculation", b"start_calculation"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["command", b"command", "shutdown", b"shutdown", "start_calculation", b"start_calculation", "timestamp", b"timestamp", "uuid", b"uuid"]) -> None: ...
    def WhichOneof(self, oneof_group: typing_extensions.Literal["command", b"command"]) -> typing_extensions.Literal["start_calculation", "shutdown"] | None: ...

global___LoadflowServiceCommand = LoadflowServiceCommand

class LoadflowResults(google.protobuf.message.Message):
    """Placeholder for LoadflowResults"""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    JOB_ID_FIELD_NUMBER: builtins.int
    RESULTS_DATA_FIELD_NUMBER: builtins.int
    job_id: builtins.str
    """Reference to job.id"""
    results_data: builtins.str
    """Serialized results data"""
    def __init__(
        self,
        *,
        job_id: builtins.str = ...,
        results_data: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["job_id", b"job_id", "results_data", b"results_data"]) -> None: ...

global___LoadflowResults = LoadflowResults

class LoadflowResultsList(google.protobuf.message.Message):
    """List of loadflow resultsf"""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    RESULTS_FIELD_NUMBER: builtins.int
    @property
    def results(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___LoadflowResults]: ...
    def __init__(
        self,
        *,
        results: collections.abc.Iterable[global___LoadflowResults] | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["results", b"results"]) -> None: ...

global___LoadflowResultsList = LoadflowResultsList
