# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: toop_engine_interfaces/messages/protobuf_schema/lf_service/loadflow_heartbeat.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='toop_engine_interfaces/messages/protobuf_schema/lf_service/loadflow_heartbeat.proto',
  package='messages.lf_service',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\nStoop_engine_interfaces/messages/protobuf_schema/lf_service/loadflow_heartbeat.proto\x12\x13messages.lf_service\"K\n\x12LoadflowStatusInfo\x12\x13\n\x0bloadflow_id\x18\x01 \x01(\t\x12\x0f\n\x07runtime\x18\x02 \x01(\x01\x12\x0f\n\x07message\x18\x03 \x01(\t\"\x80\x01\n\x11LoadflowHeartbeat\x12\x0c\n\x04idle\x18\x01 \x01(\x08\x12<\n\x0bstatus_info\x18\x02 \x01(\x0b\x32\'.messages.lf_service.LoadflowStatusInfo\x12\x11\n\ttimestamp\x18\x03 \x01(\t\x12\x0c\n\x04uuid\x18\x04 \x01(\tb\x06proto3'
)




_LOADFLOWSTATUSINFO = _descriptor.Descriptor(
  name='LoadflowStatusInfo',
  full_name='messages.lf_service.LoadflowStatusInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='loadflow_id', full_name='messages.lf_service.LoadflowStatusInfo.loadflow_id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='runtime', full_name='messages.lf_service.LoadflowStatusInfo.runtime', index=1,
      number=2, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='message', full_name='messages.lf_service.LoadflowStatusInfo.message', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=108,
  serialized_end=183,
)


_LOADFLOWHEARTBEAT = _descriptor.Descriptor(
  name='LoadflowHeartbeat',
  full_name='messages.lf_service.LoadflowHeartbeat',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='idle', full_name='messages.lf_service.LoadflowHeartbeat.idle', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='status_info', full_name='messages.lf_service.LoadflowHeartbeat.status_info', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='timestamp', full_name='messages.lf_service.LoadflowHeartbeat.timestamp', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='uuid', full_name='messages.lf_service.LoadflowHeartbeat.uuid', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=186,
  serialized_end=314,
)

_LOADFLOWHEARTBEAT.fields_by_name['status_info'].message_type = _LOADFLOWSTATUSINFO
DESCRIPTOR.message_types_by_name['LoadflowStatusInfo'] = _LOADFLOWSTATUSINFO
DESCRIPTOR.message_types_by_name['LoadflowHeartbeat'] = _LOADFLOWHEARTBEAT
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

LoadflowStatusInfo = _reflection.GeneratedProtocolMessageType('LoadflowStatusInfo', (_message.Message,), {
  'DESCRIPTOR' : _LOADFLOWSTATUSINFO,
  '__module__' : 'toop_engine_interfaces.messages.protobuf_schema.lf_service.loadflow_heartbeat_pb2'
  # @@protoc_insertion_point(class_scope:messages.lf_service.LoadflowStatusInfo)
  })
_sym_db.RegisterMessage(LoadflowStatusInfo)

LoadflowHeartbeat = _reflection.GeneratedProtocolMessageType('LoadflowHeartbeat', (_message.Message,), {
  'DESCRIPTOR' : _LOADFLOWHEARTBEAT,
  '__module__' : 'toop_engine_interfaces.messages.protobuf_schema.lf_service.loadflow_heartbeat_pb2'
  # @@protoc_insertion_point(class_scope:messages.lf_service.LoadflowHeartbeat)
  })
_sym_db.RegisterMessage(LoadflowHeartbeat)


# @@protoc_insertion_point(module_scope)
