"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""
import builtins
import google.protobuf.descriptor
import google.protobuf.message
import sys

if sys.version_info >= (3, 8):
    import typing as typing_extensions
else:
    import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

class LoadflowStatusInfo(google.protobuf.message.Message):
    """=====================================================
    LOADFLOW HEARTBEAT DEFINITIONS
    =====================================================

    Provides status information about an ongoing Loadflow solving action.
    """

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    LOADFLOW_ID_FIELD_NUMBER: builtins.int
    RUNTIME_FIELD_NUMBER: builtins.int
    MESSAGE_FIELD_NUMBER: builtins.int
    loadflow_id: builtins.str
    """The id of the loadflow solving job."""
    runtime: builtins.float
    """The amount of time since the start of the optimization (in seconds)."""
    message: builtins.str
    """An optional message."""
    def __init__(
        self,
        *,
        loadflow_id: builtins.str = ...,
        runtime: builtins.float = ...,
        message: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["loadflow_id", b"loadflow_id", "message", b"message", "runtime", b"runtime"]) -> None: ...

global___LoadflowStatusInfo = LoadflowStatusInfo

class LoadflowHeartbeat(google.protobuf.message.Message):
    """A message class for heartbeats from the loadflow worker.
    When idle, this just sends a hello; when solving, it also conveys the current status.
    """

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    IDLE_FIELD_NUMBER: builtins.int
    STATUS_INFO_FIELD_NUMBER: builtins.int
    TIMESTAMP_FIELD_NUMBER: builtins.int
    UUID_FIELD_NUMBER: builtins.int
    idle: builtins.bool
    """Whether the worker is idle."""
    @property
    def status_info(self) -> global___LoadflowStatusInfo:
        """If not idle, a status update."""
    timestamp: builtins.str
    """When the heartbeat was sent."""
    uuid: builtins.str
    """Unique identifier for this heartbeat message, used to avoid duplicates."""
    def __init__(
        self,
        *,
        idle: builtins.bool = ...,
        status_info: global___LoadflowStatusInfo | None = ...,
        timestamp: builtins.str = ...,
        uuid: builtins.str = ...,
    ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["status_info", b"status_info"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["idle", b"idle", "status_info", b"status_info", "timestamp", b"timestamp", "uuid", b"uuid"]) -> None: ...

global___LoadflowHeartbeat = LoadflowHeartbeat
