# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: toop_engine_interfaces/messages/protobuf_schema/optimizer/ac_dc_commons.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='toop_engine_interfaces/messages/protobuf_schema/optimizer/ac_dc_commons.proto',
  package='messages.optimizer',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\nMtoop_engine_interfaces/messages/protobuf_schema/optimizer/ac_dc_commons.proto\x12\x12messages.optimizer\"b\n\x08GridFile\x12\x0e\n\x06string\x18\x01 \x01(\t\x12\x13\n\x0bgrid_folder\x18\x02 \x01(\t\x12\x1f\n\x17timestep_correspondence\x18\x03 \x01(\t\x12\x10\n\x08\x63oupling\x18\x04 \x01(\t\"A\n\rDescriptorDef\x12\x0e\n\x06metric\x18\x01 \x01(\t\x12\x11\n\tnum_cells\x18\x02 \x01(\r\x12\r\n\x05range\x18\x03 \x03(\x01\"4\n\x14\x44oubleLimitsSetpoint\x12\r\n\x05lower\x18\x01 \x01(\x01\x12\r\n\x05upper\x18\x02 \x01(\x01\"\xb8\x04\n\x0e\x46ilterStrategy\x12\'\n\x1f\x66ilter_dominator_metrics_target\x18\x01 \x03(\t\x12)\n!filter_dominator_metrics_observed\x18\x02 \x03(\t\x12y\n%filter_discriminator_metric_distances\x18\x03 \x03(\x0b\x32J.messages.optimizer.FilterStrategy.FilterDiscriminatorMetricDistancesEntry\x12{\n&filter_discriminator_metric_multiplier\x18\x04 \x03(\x0b\x32K.messages.optimizer.FilterStrategy.FilterDiscriminatorMetricMultiplierEntry\x12\x1c\n\x14\x66ilter_median_metric\x18\x05 \x03(\t\x1ap\n\'FilterDiscriminatorMetricDistancesEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\x34\n\x05value\x18\x02 \x01(\x0b\x32%.messages.optimizer.FilterDistanceSet:\x02\x38\x01\x1aJ\n(FilterDiscriminatorMetricMultiplierEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\x01:\x02\x38\x01\"&\n\x11\x46ilterDistanceSet\x12\x11\n\tdistances\x18\x01 \x03(\x01\x62\x06proto3'
)




_GRIDFILE = _descriptor.Descriptor(
  name='GridFile',
  full_name='messages.optimizer.GridFile',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='string', full_name='messages.optimizer.GridFile.string', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='grid_folder', full_name='messages.optimizer.GridFile.grid_folder', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='timestep_correspondence', full_name='messages.optimizer.GridFile.timestep_correspondence', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='coupling', full_name='messages.optimizer.GridFile.coupling', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=101,
  serialized_end=199,
)


_DESCRIPTORDEF = _descriptor.Descriptor(
  name='DescriptorDef',
  full_name='messages.optimizer.DescriptorDef',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='metric', full_name='messages.optimizer.DescriptorDef.metric', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='num_cells', full_name='messages.optimizer.DescriptorDef.num_cells', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='range', full_name='messages.optimizer.DescriptorDef.range', index=2,
      number=3, type=1, cpp_type=5, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=201,
  serialized_end=266,
)


_DOUBLELIMITSSETPOINT = _descriptor.Descriptor(
  name='DoubleLimitsSetpoint',
  full_name='messages.optimizer.DoubleLimitsSetpoint',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='lower', full_name='messages.optimizer.DoubleLimitsSetpoint.lower', index=0,
      number=1, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='upper', full_name='messages.optimizer.DoubleLimitsSetpoint.upper', index=1,
      number=2, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=268,
  serialized_end=320,
)


_FILTERSTRATEGY_FILTERDISCRIMINATORMETRICDISTANCESENTRY = _descriptor.Descriptor(
  name='FilterDiscriminatorMetricDistancesEntry',
  full_name='messages.optimizer.FilterStrategy.FilterDiscriminatorMetricDistancesEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='messages.optimizer.FilterStrategy.FilterDiscriminatorMetricDistancesEntry.key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='value', full_name='messages.optimizer.FilterStrategy.FilterDiscriminatorMetricDistancesEntry.value', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=b'8\001',
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=703,
  serialized_end=815,
)

_FILTERSTRATEGY_FILTERDISCRIMINATORMETRICMULTIPLIERENTRY = _descriptor.Descriptor(
  name='FilterDiscriminatorMetricMultiplierEntry',
  full_name='messages.optimizer.FilterStrategy.FilterDiscriminatorMetricMultiplierEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='messages.optimizer.FilterStrategy.FilterDiscriminatorMetricMultiplierEntry.key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='value', full_name='messages.optimizer.FilterStrategy.FilterDiscriminatorMetricMultiplierEntry.value', index=1,
      number=2, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=b'8\001',
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=817,
  serialized_end=891,
)

_FILTERSTRATEGY = _descriptor.Descriptor(
  name='FilterStrategy',
  full_name='messages.optimizer.FilterStrategy',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='filter_dominator_metrics_target', full_name='messages.optimizer.FilterStrategy.filter_dominator_metrics_target', index=0,
      number=1, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='filter_dominator_metrics_observed', full_name='messages.optimizer.FilterStrategy.filter_dominator_metrics_observed', index=1,
      number=2, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='filter_discriminator_metric_distances', full_name='messages.optimizer.FilterStrategy.filter_discriminator_metric_distances', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='filter_discriminator_metric_multiplier', full_name='messages.optimizer.FilterStrategy.filter_discriminator_metric_multiplier', index=3,
      number=4, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='filter_median_metric', full_name='messages.optimizer.FilterStrategy.filter_median_metric', index=4,
      number=5, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[_FILTERSTRATEGY_FILTERDISCRIMINATORMETRICDISTANCESENTRY, _FILTERSTRATEGY_FILTERDISCRIMINATORMETRICMULTIPLIERENTRY, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=323,
  serialized_end=891,
)


_FILTERDISTANCESET = _descriptor.Descriptor(
  name='FilterDistanceSet',
  full_name='messages.optimizer.FilterDistanceSet',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='distances', full_name='messages.optimizer.FilterDistanceSet.distances', index=0,
      number=1, type=1, cpp_type=5, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=893,
  serialized_end=931,
)

_FILTERSTRATEGY_FILTERDISCRIMINATORMETRICDISTANCESENTRY.fields_by_name['value'].message_type = _FILTERDISTANCESET
_FILTERSTRATEGY_FILTERDISCRIMINATORMETRICDISTANCESENTRY.containing_type = _FILTERSTRATEGY
_FILTERSTRATEGY_FILTERDISCRIMINATORMETRICMULTIPLIERENTRY.containing_type = _FILTERSTRATEGY
_FILTERSTRATEGY.fields_by_name['filter_discriminator_metric_distances'].message_type = _FILTERSTRATEGY_FILTERDISCRIMINATORMETRICDISTANCESENTRY
_FILTERSTRATEGY.fields_by_name['filter_discriminator_metric_multiplier'].message_type = _FILTERSTRATEGY_FILTERDISCRIMINATORMETRICMULTIPLIERENTRY
DESCRIPTOR.message_types_by_name['GridFile'] = _GRIDFILE
DESCRIPTOR.message_types_by_name['DescriptorDef'] = _DESCRIPTORDEF
DESCRIPTOR.message_types_by_name['DoubleLimitsSetpoint'] = _DOUBLELIMITSSETPOINT
DESCRIPTOR.message_types_by_name['FilterStrategy'] = _FILTERSTRATEGY
DESCRIPTOR.message_types_by_name['FilterDistanceSet'] = _FILTERDISTANCESET
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

GridFile = _reflection.GeneratedProtocolMessageType('GridFile', (_message.Message,), {
  'DESCRIPTOR' : _GRIDFILE,
  '__module__' : 'toop_engine_interfaces.messages.protobuf_schema.optimizer.ac_dc_commons_pb2'
  # @@protoc_insertion_point(class_scope:messages.optimizer.GridFile)
  })
_sym_db.RegisterMessage(GridFile)

DescriptorDef = _reflection.GeneratedProtocolMessageType('DescriptorDef', (_message.Message,), {
  'DESCRIPTOR' : _DESCRIPTORDEF,
  '__module__' : 'toop_engine_interfaces.messages.protobuf_schema.optimizer.ac_dc_commons_pb2'
  # @@protoc_insertion_point(class_scope:messages.optimizer.DescriptorDef)
  })
_sym_db.RegisterMessage(DescriptorDef)

DoubleLimitsSetpoint = _reflection.GeneratedProtocolMessageType('DoubleLimitsSetpoint', (_message.Message,), {
  'DESCRIPTOR' : _DOUBLELIMITSSETPOINT,
  '__module__' : 'toop_engine_interfaces.messages.protobuf_schema.optimizer.ac_dc_commons_pb2'
  # @@protoc_insertion_point(class_scope:messages.optimizer.DoubleLimitsSetpoint)
  })
_sym_db.RegisterMessage(DoubleLimitsSetpoint)

FilterStrategy = _reflection.GeneratedProtocolMessageType('FilterStrategy', (_message.Message,), {

  'FilterDiscriminatorMetricDistancesEntry' : _reflection.GeneratedProtocolMessageType('FilterDiscriminatorMetricDistancesEntry', (_message.Message,), {
    'DESCRIPTOR' : _FILTERSTRATEGY_FILTERDISCRIMINATORMETRICDISTANCESENTRY,
    '__module__' : 'toop_engine_interfaces.messages.protobuf_schema.optimizer.ac_dc_commons_pb2'
    # @@protoc_insertion_point(class_scope:messages.optimizer.FilterStrategy.FilterDiscriminatorMetricDistancesEntry)
    })
  ,

  'FilterDiscriminatorMetricMultiplierEntry' : _reflection.GeneratedProtocolMessageType('FilterDiscriminatorMetricMultiplierEntry', (_message.Message,), {
    'DESCRIPTOR' : _FILTERSTRATEGY_FILTERDISCRIMINATORMETRICMULTIPLIERENTRY,
    '__module__' : 'toop_engine_interfaces.messages.protobuf_schema.optimizer.ac_dc_commons_pb2'
    # @@protoc_insertion_point(class_scope:messages.optimizer.FilterStrategy.FilterDiscriminatorMetricMultiplierEntry)
    })
  ,
  'DESCRIPTOR' : _FILTERSTRATEGY,
  '__module__' : 'toop_engine_interfaces.messages.protobuf_schema.optimizer.ac_dc_commons_pb2'
  # @@protoc_insertion_point(class_scope:messages.optimizer.FilterStrategy)
  })
_sym_db.RegisterMessage(FilterStrategy)
_sym_db.RegisterMessage(FilterStrategy.FilterDiscriminatorMetricDistancesEntry)
_sym_db.RegisterMessage(FilterStrategy.FilterDiscriminatorMetricMultiplierEntry)

FilterDistanceSet = _reflection.GeneratedProtocolMessageType('FilterDistanceSet', (_message.Message,), {
  'DESCRIPTOR' : _FILTERDISTANCESET,
  '__module__' : 'toop_engine_interfaces.messages.protobuf_schema.optimizer.ac_dc_commons_pb2'
  # @@protoc_insertion_point(class_scope:messages.optimizer.FilterDistanceSet)
  })
_sym_db.RegisterMessage(FilterDistanceSet)


_FILTERSTRATEGY_FILTERDISCRIMINATORMETRICDISTANCESENTRY._options = None
_FILTERSTRATEGY_FILTERDISCRIMINATORMETRICMULTIPLIERENTRY._options = None
# @@protoc_insertion_point(module_scope)
