"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""
import builtins
import collections.abc
import google.protobuf.descriptor
import google.protobuf.internal.containers
import google.protobuf.message
import sys

if sys.version_info >= (3, 8):
    import typing as typing_extensions
else:
    import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

class GridFile(google.protobuf.message.Message):
    """=====================================================
    GRID FILE DEFINITION
    =====================================================

    Holds information about the grid files to load.

    This refers to a grid folder for a single timestep. 
    For every timestep to be optimized, there is one GridFile object.
    The coupling field defines how timesteps are related.
    """

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    STRING_FIELD_NUMBER: builtins.int
    GRID_FOLDER_FIELD_NUMBER: builtins.int
    TIMESTEP_CORRESPONDENCE_FIELD_NUMBER: builtins.int
    COUPLING_FIELD_NUMBER: builtins.int
    string: builtins.str
    """Which modelling software can read the grid file."""
    grid_folder: builtins.str
    """Path to the scenario grid folder (relative, not absolute).
    Should comply with the folder structure defined in `interfaces.folder_structure`.
    Workers prefix the full base path.
    """
    timestep_correspondence: builtins.str
    """The timestep correspondence to real-world time, if available (ISO 8601 datetime string)."""
    coupling: builtins.str
    """How this timestep is coupled to the previous timestep.

    Possible values:
    - "loose": shared PTDF matrix, different topologies
    - "tight": shared PTDF matrix and topology
    - "none": independent PTDF and topology

    The first timestep is always uncoupled.
    TODO: not yet used.
    """
    def __init__(
        self,
        *,
        string: builtins.str = ...,
        grid_folder: builtins.str = ...,
        timestep_correspondence: builtins.str = ...,
        coupling: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["coupling", b"coupling", "grid_folder", b"grid_folder", "string", b"string", "timestep_correspondence", b"timestep_correspondence"]) -> None: ...

global___GridFile = GridFile

class DescriptorDef(google.protobuf.message.Message):
    """=====================================================
    DESCRIPTOR DEFINITION
    =====================================================

    A descriptor definition for the MAP-Elites algorithm,
    defining the dimension of the repertoire.
    """

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    METRIC_FIELD_NUMBER: builtins.int
    NUM_CELLS_FIELD_NUMBER: builtins.int
    RANGE_FIELD_NUMBER: builtins.int
    metric: builtins.str
    """The metric to use for the descriptor. 
    Must correspond to an integer-type metric.
    """
    num_cells: builtins.int
    """Number of cells to use for the descriptor."""
    @property
    def range(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.float]:
        """Range of the descriptor dimension defined by min and max values.
        If not given, 0..num_cells will be used.
        """
    def __init__(
        self,
        *,
        metric: builtins.str = ...,
        num_cells: builtins.int = ...,
        range: collections.abc.Iterable[builtins.float] | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["metric", b"metric", "num_cells", b"num_cells", "range", b"range"]) -> None: ...

global___DescriptorDef = DescriptorDef

class DoubleLimitsSetpoint(google.protobuf.message.Message):
    """=====================================================
    DOUBLE LIMITS SETPOINT
    =====================================================

    A setpoint for the double limits, consisting of a lower and upper limit.

    Will be passed to `update_max_mw_flows_according_to_double_limits`.
    """

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    LOWER_FIELD_NUMBER: builtins.int
    UPPER_FIELD_NUMBER: builtins.int
    lower: builtins.float
    """The new lower limit. 1.0 leaves it unchanged."""
    upper: builtins.float
    """The new upper limit. 1.0 leaves it unchanged."""
    def __init__(
        self,
        *,
        lower: builtins.float = ...,
        upper: builtins.float = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["lower", b"lower", "upper", b"upper"]) -> None: ...

global___DoubleLimitsSetpoint = DoubleLimitsSetpoint

class FilterStrategy(google.protobuf.message.Message):
    """=====================================================
    FILTER STRATEGY
    =====================================================

    A filter strategy to pull strategies from the DC repertoire.
    """

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    class FilterDiscriminatorMetricDistancesEntry(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor

        KEY_FIELD_NUMBER: builtins.int
        VALUE_FIELD_NUMBER: builtins.int
        key: builtins.str
        @property
        def value(self) -> global___FilterDistanceSet: ...
        def __init__(
            self,
            *,
            key: builtins.str = ...,
            value: global___FilterDistanceSet | None = ...,
        ) -> None: ...
        def HasField(self, field_name: typing_extensions.Literal["value", b"value"]) -> builtins.bool: ...
        def ClearField(self, field_name: typing_extensions.Literal["key", b"key", "value", b"value"]) -> None: ...

    class FilterDiscriminatorMetricMultiplierEntry(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor

        KEY_FIELD_NUMBER: builtins.int
        VALUE_FIELD_NUMBER: builtins.int
        key: builtins.str
        value: builtins.float
        def __init__(
            self,
            *,
            key: builtins.str = ...,
            value: builtins.float = ...,
        ) -> None: ...
        def ClearField(self, field_name: typing_extensions.Literal["key", b"key", "value", b"value"]) -> None: ...

    FILTER_DOMINATOR_METRICS_TARGET_FIELD_NUMBER: builtins.int
    FILTER_DOMINATOR_METRICS_OBSERVED_FIELD_NUMBER: builtins.int
    FILTER_DISCRIMINATOR_METRIC_DISTANCES_FIELD_NUMBER: builtins.int
    FILTER_DISCRIMINATOR_METRIC_MULTIPLIER_FIELD_NUMBER: builtins.int
    FILTER_MEDIAN_METRIC_FIELD_NUMBER: builtins.int
    @property
    def filter_dominator_metrics_target(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.str]:
        """Whether to use the dominator filter for pulling strategies from the DC repertoire.
        A dominator is a metric entry with no other entry with a better fitness 
        relative to the distance to the original topology.

        The target metrics are discrete (e.g., split_subs, disconnected_branches).
        Example: ["switching_distance", "split_subs"]
        """
    @property
    def filter_dominator_metrics_observed(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.str]:
        """Whether to use the dominator filter for observed metrics.
        Observed metrics may include both discrete and continuous values.
        Example: ["switching_distance", "split_subs"]
        """
    @property
    def filter_discriminator_metric_distances(self) -> google.protobuf.internal.containers.MessageMap[builtins.str, global___FilterDistanceSet]:
        """Distances for metrics used in the discriminator filter.
        The key is the metric name (or "fitness"), and the value is a set of distances.

        Example:
        {
          "split_subs": {0.0, 0.0},
          "switching_distance": {-0.9, 0.9},
          "fitness": {-0.1, 0.1}
        }
        """
    @property
    def filter_discriminator_metric_multiplier(self) -> google.protobuf.internal.containers.ScalarMap[builtins.str, builtins.float]:
        """Multiplier dictionary for metric distances.
        Defines how strongly each metric contributes to distance-based filtering.

        Example:
        {"split_subs": 0.5}

        Formula:
        distance_multiplier = (
          metric_multiplier[metric1] * discriminator_df[metric1] +
          metric_multiplier[metric2] * discriminator_df[metric2] + ...
        )
        """
    @property
    def filter_median_metric(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.str]:
        """Whether to use the median filter for pulling strategies.
        Expects discrete target metrics (e.g., split_subs, disconnected_branches).

        Example:
        ["split_subs"]
        """
    def __init__(
        self,
        *,
        filter_dominator_metrics_target: collections.abc.Iterable[builtins.str] | None = ...,
        filter_dominator_metrics_observed: collections.abc.Iterable[builtins.str] | None = ...,
        filter_discriminator_metric_distances: collections.abc.Mapping[builtins.str, global___FilterDistanceSet] | None = ...,
        filter_discriminator_metric_multiplier: collections.abc.Mapping[builtins.str, builtins.float] | None = ...,
        filter_median_metric: collections.abc.Iterable[builtins.str] | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["filter_discriminator_metric_distances", b"filter_discriminator_metric_distances", "filter_discriminator_metric_multiplier", b"filter_discriminator_metric_multiplier", "filter_dominator_metrics_observed", b"filter_dominator_metrics_observed", "filter_dominator_metrics_target", b"filter_dominator_metrics_target", "filter_median_metric", b"filter_median_metric"]) -> None: ...

global___FilterStrategy = FilterStrategy

class FilterDistanceSet(google.protobuf.message.Message):
    """Represents a set of distances for a metric (since proto3 lacks a native "set" type)."""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    DISTANCES_FIELD_NUMBER: builtins.int
    @property
    def distances(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.float]:
        """Distances used for filtering."""
    def __init__(
        self,
        *,
        distances: collections.abc.Iterable[builtins.float] | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["distances", b"distances"]) -> None: ...

global___FilterDistanceSet = FilterDistanceSet
