# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: toop_engine_interfaces/messages/protobuf_schema/optimizer/ac_optimizer_params.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from toop_engine_interfaces.messages.protobuf_schema.lf_service import stored_loadflow_reference_pb2 as toop__engine__interfaces_dot_messages_dot_protobuf__schema_dot_lf__service_dot_stored__loadflow__reference__pb2
from toop_engine_interfaces.messages.protobuf_schema.optimizer import ac_dc_commons_pb2 as toop__engine__interfaces_dot_messages_dot_protobuf__schema_dot_optimizer_dot_ac__dc__commons__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='toop_engine_interfaces/messages/protobuf_schema/optimizer/ac_optimizer_params.proto',
  package='messages.optimizer',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\nStoop_engine_interfaces/messages/protobuf_schema/optimizer/ac_optimizer_params.proto\x12\x12messages.optimizer\x1aZtoop_engine_interfaces/messages/protobuf_schema/lf_service/stored_loadflow_reference.proto\x1aMtoop_engine_interfaces/messages/protobuf_schema/optimizer/ac_dc_commons.proto\"\xea\x04\n\x0e\x41\x43GAParameters\x12\x17\n\x0fruntime_seconds\x18\x01 \x01(\r\x12\x11\n\tpull_prob\x18\x02 \x01(\x01\x12\x39\n\x0eme_descriptors\x18\x03 \x03(\x0b\x32!.messages.optimizer.DescriptorDef\x12\x16\n\x0ereconnect_prob\x18\x04 \x01(\x01\x12\x1a\n\x12\x63lose_coupler_prob\x18\x05 \x01(\x01\x12\x1d\n\x15n_worst_contingencies\x18\x06 \x01(\r\x12\x0c\n\x04seed\x18\x07 \x01(\x05\x12\x1a\n\x12timestep_processes\x18\x08 \x01(\r\x12\x18\n\x10runner_processes\x18\t \x01(\r\x12\x18\n\x10runner_batchsize\x18\n \x01(\r\x12@\n\x0f\x66ilter_strategy\x18\x0b \x01(\x0b\x32\".messages.optimizer.FilterStrategyH\x00\x88\x01\x01\x12\x1b\n\x13\x65nable_ac_rejection\x18\x0c \x01(\x08\x12$\n\x1creject_convergence_threshold\x18\r \x01(\x01\x12!\n\x19reject_overload_threshold\x18\x0e \x01(\x01\x12(\n reject_critical_branch_threshold\x18\x0f \x01(\x01\x12\x1d\n\x15\x65\x61rly_stop_validation\x18\x10 \x01(\x08\x12;\n3early_stopping_non_convergence_percentage_threshold\x18\x11 \x01(\x01\x42\x12\n\x10_filter_strategy\"\x96\x01\n\x15\x41\x43OptimizerParameters\x12\x46\n\x10initial_loadflow\x18\x01 \x01(\x0b\x32,.messages.lf_service.StoredLoadflowReference\x12\x35\n\tga_config\x18\x02 \x01(\x0b\x32\".messages.optimizer.ACGAParametersb\x06proto3'
  ,
  dependencies=[toop__engine__interfaces_dot_messages_dot_protobuf__schema_dot_lf__service_dot_stored__loadflow__reference__pb2.DESCRIPTOR,toop__engine__interfaces_dot_messages_dot_protobuf__schema_dot_optimizer_dot_ac__dc__commons__pb2.DESCRIPTOR,])




_ACGAPARAMETERS = _descriptor.Descriptor(
  name='ACGAParameters',
  full_name='messages.optimizer.ACGAParameters',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='runtime_seconds', full_name='messages.optimizer.ACGAParameters.runtime_seconds', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='pull_prob', full_name='messages.optimizer.ACGAParameters.pull_prob', index=1,
      number=2, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='me_descriptors', full_name='messages.optimizer.ACGAParameters.me_descriptors', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='reconnect_prob', full_name='messages.optimizer.ACGAParameters.reconnect_prob', index=3,
      number=4, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='close_coupler_prob', full_name='messages.optimizer.ACGAParameters.close_coupler_prob', index=4,
      number=5, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='n_worst_contingencies', full_name='messages.optimizer.ACGAParameters.n_worst_contingencies', index=5,
      number=6, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='seed', full_name='messages.optimizer.ACGAParameters.seed', index=6,
      number=7, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='timestep_processes', full_name='messages.optimizer.ACGAParameters.timestep_processes', index=7,
      number=8, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='runner_processes', full_name='messages.optimizer.ACGAParameters.runner_processes', index=8,
      number=9, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='runner_batchsize', full_name='messages.optimizer.ACGAParameters.runner_batchsize', index=9,
      number=10, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='filter_strategy', full_name='messages.optimizer.ACGAParameters.filter_strategy', index=10,
      number=11, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='enable_ac_rejection', full_name='messages.optimizer.ACGAParameters.enable_ac_rejection', index=11,
      number=12, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='reject_convergence_threshold', full_name='messages.optimizer.ACGAParameters.reject_convergence_threshold', index=12,
      number=13, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='reject_overload_threshold', full_name='messages.optimizer.ACGAParameters.reject_overload_threshold', index=13,
      number=14, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='reject_critical_branch_threshold', full_name='messages.optimizer.ACGAParameters.reject_critical_branch_threshold', index=14,
      number=15, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='early_stop_validation', full_name='messages.optimizer.ACGAParameters.early_stop_validation', index=15,
      number=16, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='early_stopping_non_convergence_percentage_threshold', full_name='messages.optimizer.ACGAParameters.early_stopping_non_convergence_percentage_threshold', index=16,
      number=17, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='_filter_strategy', full_name='messages.optimizer.ACGAParameters._filter_strategy',
      index=0, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
  ],
  serialized_start=279,
  serialized_end=897,
)


_ACOPTIMIZERPARAMETERS = _descriptor.Descriptor(
  name='ACOptimizerParameters',
  full_name='messages.optimizer.ACOptimizerParameters',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='initial_loadflow', full_name='messages.optimizer.ACOptimizerParameters.initial_loadflow', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='ga_config', full_name='messages.optimizer.ACOptimizerParameters.ga_config', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=900,
  serialized_end=1050,
)

_ACGAPARAMETERS.fields_by_name['me_descriptors'].message_type = toop__engine__interfaces_dot_messages_dot_protobuf__schema_dot_optimizer_dot_ac__dc__commons__pb2._DESCRIPTORDEF
_ACGAPARAMETERS.fields_by_name['filter_strategy'].message_type = toop__engine__interfaces_dot_messages_dot_protobuf__schema_dot_optimizer_dot_ac__dc__commons__pb2._FILTERSTRATEGY
_ACGAPARAMETERS.oneofs_by_name['_filter_strategy'].fields.append(
  _ACGAPARAMETERS.fields_by_name['filter_strategy'])
_ACGAPARAMETERS.fields_by_name['filter_strategy'].containing_oneof = _ACGAPARAMETERS.oneofs_by_name['_filter_strategy']
_ACOPTIMIZERPARAMETERS.fields_by_name['initial_loadflow'].message_type = toop__engine__interfaces_dot_messages_dot_protobuf__schema_dot_lf__service_dot_stored__loadflow__reference__pb2._STOREDLOADFLOWREFERENCE
_ACOPTIMIZERPARAMETERS.fields_by_name['ga_config'].message_type = _ACGAPARAMETERS
DESCRIPTOR.message_types_by_name['ACGAParameters'] = _ACGAPARAMETERS
DESCRIPTOR.message_types_by_name['ACOptimizerParameters'] = _ACOPTIMIZERPARAMETERS
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ACGAParameters = _reflection.GeneratedProtocolMessageType('ACGAParameters', (_message.Message,), {
  'DESCRIPTOR' : _ACGAPARAMETERS,
  '__module__' : 'toop_engine_interfaces.messages.protobuf_schema.optimizer.ac_optimizer_params_pb2'
  # @@protoc_insertion_point(class_scope:messages.optimizer.ACGAParameters)
  })
_sym_db.RegisterMessage(ACGAParameters)

ACOptimizerParameters = _reflection.GeneratedProtocolMessageType('ACOptimizerParameters', (_message.Message,), {
  'DESCRIPTOR' : _ACOPTIMIZERPARAMETERS,
  '__module__' : 'toop_engine_interfaces.messages.protobuf_schema.optimizer.ac_optimizer_params_pb2'
  # @@protoc_insertion_point(class_scope:messages.optimizer.ACOptimizerParameters)
  })
_sym_db.RegisterMessage(ACOptimizerParameters)


# @@protoc_insertion_point(module_scope)
