"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""
import builtins
import collections.abc
import google.protobuf.descriptor
import google.protobuf.internal.containers
import google.protobuf.message
import sys
import toop_engine_interfaces.messages.protobuf_schema.lf_service.stored_loadflow_reference_pb2
import toop_engine_interfaces.messages.protobuf_schema.optimizer.ac_dc_commons_pb2

if sys.version_info >= (3, 8):
    import typing as typing_extensions
else:
    import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

class ACGAParameters(google.protobuf.message.Message):
    """=====================================================
    AC GENETIC ALGORITHM PARAMETERS
    =====================================================

    Parameters for the AC genetic algorithm.
    """

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    RUNTIME_SECONDS_FIELD_NUMBER: builtins.int
    PULL_PROB_FIELD_NUMBER: builtins.int
    ME_DESCRIPTORS_FIELD_NUMBER: builtins.int
    RECONNECT_PROB_FIELD_NUMBER: builtins.int
    CLOSE_COUPLER_PROB_FIELD_NUMBER: builtins.int
    N_WORST_CONTINGENCIES_FIELD_NUMBER: builtins.int
    SEED_FIELD_NUMBER: builtins.int
    TIMESTEP_PROCESSES_FIELD_NUMBER: builtins.int
    RUNNER_PROCESSES_FIELD_NUMBER: builtins.int
    RUNNER_BATCHSIZE_FIELD_NUMBER: builtins.int
    FILTER_STRATEGY_FIELD_NUMBER: builtins.int
    ENABLE_AC_REJECTION_FIELD_NUMBER: builtins.int
    REJECT_CONVERGENCE_THRESHOLD_FIELD_NUMBER: builtins.int
    REJECT_OVERLOAD_THRESHOLD_FIELD_NUMBER: builtins.int
    REJECT_CRITICAL_BRANCH_THRESHOLD_FIELD_NUMBER: builtins.int
    EARLY_STOP_VALIDATION_FIELD_NUMBER: builtins.int
    EARLY_STOPPING_NON_CONVERGENCE_PERCENTAGE_THRESHOLD_FIELD_NUMBER: builtins.int
    runtime_seconds: builtins.int
    """The maximum runtime of the AC optimization in seconds."""
    pull_prob: builtins.float
    """The probability of pulling a strategy from the DC repertoire."""
    @property
    def me_descriptors(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[toop_engine_interfaces.messages.protobuf_schema.optimizer.ac_dc_commons_pb2.DescriptorDef]:
        """The descriptors for the aggregated map elites repertoire."""
    reconnect_prob: builtins.float
    """The probability of reconnecting a disconnected branch in a strategy."""
    close_coupler_prob: builtins.float
    """The probability of closing an opened coupler in a strategy."""
    n_worst_contingencies: builtins.int
    """How many worst contingencies to consider for the initial metrics,
    i.e. the top k contingencies used to compute the initial metrics.
    """
    seed: builtins.int
    """The seed for the random number generator."""
    timestep_processes: builtins.int
    """How many processes to spawn for computing timesteps in parallel."""
    runner_processes: builtins.int
    """How many processes to spawn for computing N-1 cases per timestep in parallel.
    Note: This multiplies with timestep_processes and may exhaust memory if both are high.
    """
    runner_batchsize: builtins.int
    """Whether to batch the N-1 definition into smaller chunks to conserve memory."""
    @property
    def filter_strategy(self) -> toop_engine_interfaces.messages.protobuf_schema.optimizer.ac_dc_commons_pb2.FilterStrategy:
        """The filter strategy to use for the optimization, used to filter out strategies
        based on the discriminator, median, or dominator filter.
        """
    enable_ac_rejection: builtins.bool
    """Whether to enable AC rejection — i.e., suppress result messages when not accepted."""
    reject_convergence_threshold: builtins.float
    """The rejection threshold for the convergence rate:
    the split case must have at most as many non-converging loadflows as the unsplit case.
    """
    reject_overload_threshold: builtins.float
    """The rejection threshold for overload energy improvement:
    the split case must have at least 5% lower overload energy than the unsplit case.
    """
    reject_critical_branch_threshold: builtins.float
    """The rejection threshold for the critical branches increase:
    the split case must have less than 10% more critical branches than the unsplit case.
    """
    early_stop_validation: builtins.bool
    """Whether to enable early stopping during the optimization process."""
    early_stopping_non_convergence_percentage_threshold: builtins.float
    """The threshold for early stopping:
    if the percentage of non-converging cases exceeds this value,
    the AC validation will be stopped early.
    """
    def __init__(
        self,
        *,
        runtime_seconds: builtins.int = ...,
        pull_prob: builtins.float = ...,
        me_descriptors: collections.abc.Iterable[toop_engine_interfaces.messages.protobuf_schema.optimizer.ac_dc_commons_pb2.DescriptorDef] | None = ...,
        reconnect_prob: builtins.float = ...,
        close_coupler_prob: builtins.float = ...,
        n_worst_contingencies: builtins.int = ...,
        seed: builtins.int = ...,
        timestep_processes: builtins.int = ...,
        runner_processes: builtins.int = ...,
        runner_batchsize: builtins.int = ...,
        filter_strategy: toop_engine_interfaces.messages.protobuf_schema.optimizer.ac_dc_commons_pb2.FilterStrategy | None = ...,
        enable_ac_rejection: builtins.bool = ...,
        reject_convergence_threshold: builtins.float = ...,
        reject_overload_threshold: builtins.float = ...,
        reject_critical_branch_threshold: builtins.float = ...,
        early_stop_validation: builtins.bool = ...,
        early_stopping_non_convergence_percentage_threshold: builtins.float = ...,
    ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["filter_strategy", b"filter_strategy"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["close_coupler_prob", b"close_coupler_prob", "early_stop_validation", b"early_stop_validation", "early_stopping_non_convergence_percentage_threshold", b"early_stopping_non_convergence_percentage_threshold", "enable_ac_rejection", b"enable_ac_rejection", "filter_strategy", b"filter_strategy", "me_descriptors", b"me_descriptors", "n_worst_contingencies", b"n_worst_contingencies", "pull_prob", b"pull_prob", "reconnect_prob", b"reconnect_prob", "reject_convergence_threshold", b"reject_convergence_threshold", "reject_critical_branch_threshold", b"reject_critical_branch_threshold", "reject_overload_threshold", b"reject_overload_threshold", "runner_batchsize", b"runner_batchsize", "runner_processes", b"runner_processes", "runtime_seconds", b"runtime_seconds", "seed", b"seed", "timestep_processes", b"timestep_processes"]) -> None: ...

global___ACGAParameters = ACGAParameters

class ACOptimizerParameters(google.protobuf.message.Message):
    """=====================================================
    AC OPTIMIZER PARAMETERS
    =====================================================

    The set of parameters used exclusively by the AC optimizer.
    """

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    INITIAL_LOADFLOW_FIELD_NUMBER: builtins.int
    GA_CONFIG_FIELD_NUMBER: builtins.int
    @property
    def initial_loadflow(self) -> toop_engine_interfaces.messages.protobuf_schema.lf_service.stored_loadflow_reference_pb2.StoredLoadflowReference:
        """If an initial AC loadflow was computed before the optimization run,
        this can be provided and used to compute double limits.
        It will be returned through the initial topology push.
        """
    @property
    def ga_config(self) -> global___ACGAParameters:
        """The genetic algorithm configuration."""
    def __init__(
        self,
        *,
        initial_loadflow: toop_engine_interfaces.messages.protobuf_schema.lf_service.stored_loadflow_reference_pb2.StoredLoadflowReference | None = ...,
        ga_config: global___ACGAParameters | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["ga_config", b"ga_config", "initial_loadflow", b"initial_loadflow"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["ga_config", b"ga_config", "initial_loadflow", b"initial_loadflow"]) -> None: ...

global___ACOptimizerParameters = ACOptimizerParameters
