# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: toop_engine_interfaces/messages/protobuf_schema/optimizer/dc_optimizer_params.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from toop_engine_interfaces.messages.protobuf_schema.optimizer import ac_dc_commons_pb2 as toop__engine__interfaces_dot_messages_dot_protobuf__schema_dot_optimizer_dot_ac__dc__commons__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='toop_engine_interfaces/messages/protobuf_schema/optimizer/dc_optimizer_params.proto',
  package='messages.optimizer',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\nStoop_engine_interfaces/messages/protobuf_schema/optimizer/dc_optimizer_params.proto\x12\x12messages.optimizer\x1aMtoop_engine_interfaces/messages/protobuf_schema/optimizer/ac_dc_commons.proto\"\x9e\x04\n\x13\x42\x61tchedMEParameters\x12\x1d\n\x15substation_split_prob\x18\x01 \x01(\x01\x12\x1f\n\x17substation_unsplit_prob\x18\x02 \x01(\x01\x12\x17\n\x0f\x64isconnect_prob\x18\x03 \x01(\x01\x12\x16\n\x0ereconnect_prob\x18\x04 \x01(\x01\x12\x1d\n\x15n_subs_mutated_lambda\x18\x05 \x01(\x01\x12\x1c\n\x14proportion_crossover\x18\x06 \x01(\x01\x12 \n\x18\x63rossover_mutation_ratio\x18\x07 \x01(\x01\x12\x38\n\x0etarget_metrics\x18\x08 \x03(\x0b\x32 .messages.optimizer.TargetMetric\x12\x18\n\x10observed_metrics\x18\t \x03(\t\x12\x39\n\x0eme_descriptors\x18\n \x03(\x0b\x32!.messages.optimizer.DescriptorDef\x12\x17\n\x0fruntime_seconds\x18\x0b \x01(\x01\x12\x1c\n\x14iterations_per_epoch\x18\x0c \x01(\r\x12\x13\n\x0brandom_seed\x18\r \x01(\x05\x12\x12\n\ncell_depth\x18\x0e \x01(\r\x12\x0c\n\x04plot\x18\x0f \x01(\x08\x12\x1b\n\x13mutation_repetition\x18\x10 \x01(\r\x12\x1d\n\x15n_worst_contingencies\x18\x11 \x01(\r\".\n\x0cTargetMetric\x12\x0e\n\x06metric\x18\x01 \x01(\t\x12\x0e\n\x06weight\x18\x02 \x01(\x01\"\x97\x01\n\x18LoadflowSolverParameters\x12\x16\n\x0emax_num_splits\x18\x01 \x01(\r\x12\x1e\n\x16max_num_disconnections\x18\x02 \x01(\r\x12\x12\n\nbatch_size\x18\x03 \x01(\r\x12\x13\n\x0b\x64istributed\x18\x04 \x01(\x08\x12\x1a\n\x12\x63ross_coupler_flow\x18\x05 \x01(\x08\"\x9e\x02\n\x15\x44\x43OptimizerParameters\x12:\n\tga_config\x18\x01 \x01(\x0b\x32\'.messages.optimizer.BatchedMEParameters\x12L\n\x16loadflow_solver_config\x18\x02 \x01(\x0b\x32,.messages.optimizer.LoadflowSolverParameters\x12?\n\rdouble_limits\x18\x03 \x01(\x0b\x32(.messages.optimizer.DoubleLimitsSetpoint\x12\x19\n\x11summary_frequency\x18\x04 \x01(\r\x12\x1f\n\x17\x63heck_command_frequency\x18\x05 \x01(\rb\x06proto3'
  ,
  dependencies=[toop__engine__interfaces_dot_messages_dot_protobuf__schema_dot_optimizer_dot_ac__dc__commons__pb2.DESCRIPTOR,])




_BATCHEDMEPARAMETERS = _descriptor.Descriptor(
  name='BatchedMEParameters',
  full_name='messages.optimizer.BatchedMEParameters',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='substation_split_prob', full_name='messages.optimizer.BatchedMEParameters.substation_split_prob', index=0,
      number=1, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='substation_unsplit_prob', full_name='messages.optimizer.BatchedMEParameters.substation_unsplit_prob', index=1,
      number=2, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='disconnect_prob', full_name='messages.optimizer.BatchedMEParameters.disconnect_prob', index=2,
      number=3, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='reconnect_prob', full_name='messages.optimizer.BatchedMEParameters.reconnect_prob', index=3,
      number=4, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='n_subs_mutated_lambda', full_name='messages.optimizer.BatchedMEParameters.n_subs_mutated_lambda', index=4,
      number=5, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='proportion_crossover', full_name='messages.optimizer.BatchedMEParameters.proportion_crossover', index=5,
      number=6, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='crossover_mutation_ratio', full_name='messages.optimizer.BatchedMEParameters.crossover_mutation_ratio', index=6,
      number=7, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='target_metrics', full_name='messages.optimizer.BatchedMEParameters.target_metrics', index=7,
      number=8, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='observed_metrics', full_name='messages.optimizer.BatchedMEParameters.observed_metrics', index=8,
      number=9, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='me_descriptors', full_name='messages.optimizer.BatchedMEParameters.me_descriptors', index=9,
      number=10, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='runtime_seconds', full_name='messages.optimizer.BatchedMEParameters.runtime_seconds', index=10,
      number=11, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='iterations_per_epoch', full_name='messages.optimizer.BatchedMEParameters.iterations_per_epoch', index=11,
      number=12, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='random_seed', full_name='messages.optimizer.BatchedMEParameters.random_seed', index=12,
      number=13, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='cell_depth', full_name='messages.optimizer.BatchedMEParameters.cell_depth', index=13,
      number=14, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='plot', full_name='messages.optimizer.BatchedMEParameters.plot', index=14,
      number=15, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='mutation_repetition', full_name='messages.optimizer.BatchedMEParameters.mutation_repetition', index=15,
      number=16, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='n_worst_contingencies', full_name='messages.optimizer.BatchedMEParameters.n_worst_contingencies', index=16,
      number=17, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=187,
  serialized_end=729,
)


_TARGETMETRIC = _descriptor.Descriptor(
  name='TargetMetric',
  full_name='messages.optimizer.TargetMetric',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='metric', full_name='messages.optimizer.TargetMetric.metric', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='weight', full_name='messages.optimizer.TargetMetric.weight', index=1,
      number=2, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=731,
  serialized_end=777,
)


_LOADFLOWSOLVERPARAMETERS = _descriptor.Descriptor(
  name='LoadflowSolverParameters',
  full_name='messages.optimizer.LoadflowSolverParameters',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='max_num_splits', full_name='messages.optimizer.LoadflowSolverParameters.max_num_splits', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='max_num_disconnections', full_name='messages.optimizer.LoadflowSolverParameters.max_num_disconnections', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='batch_size', full_name='messages.optimizer.LoadflowSolverParameters.batch_size', index=2,
      number=3, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='distributed', full_name='messages.optimizer.LoadflowSolverParameters.distributed', index=3,
      number=4, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='cross_coupler_flow', full_name='messages.optimizer.LoadflowSolverParameters.cross_coupler_flow', index=4,
      number=5, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=780,
  serialized_end=931,
)


_DCOPTIMIZERPARAMETERS = _descriptor.Descriptor(
  name='DCOptimizerParameters',
  full_name='messages.optimizer.DCOptimizerParameters',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='ga_config', full_name='messages.optimizer.DCOptimizerParameters.ga_config', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='loadflow_solver_config', full_name='messages.optimizer.DCOptimizerParameters.loadflow_solver_config', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='double_limits', full_name='messages.optimizer.DCOptimizerParameters.double_limits', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='summary_frequency', full_name='messages.optimizer.DCOptimizerParameters.summary_frequency', index=3,
      number=4, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='check_command_frequency', full_name='messages.optimizer.DCOptimizerParameters.check_command_frequency', index=4,
      number=5, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=934,
  serialized_end=1220,
)

_BATCHEDMEPARAMETERS.fields_by_name['target_metrics'].message_type = _TARGETMETRIC
_BATCHEDMEPARAMETERS.fields_by_name['me_descriptors'].message_type = toop__engine__interfaces_dot_messages_dot_protobuf__schema_dot_optimizer_dot_ac__dc__commons__pb2._DESCRIPTORDEF
_DCOPTIMIZERPARAMETERS.fields_by_name['ga_config'].message_type = _BATCHEDMEPARAMETERS
_DCOPTIMIZERPARAMETERS.fields_by_name['loadflow_solver_config'].message_type = _LOADFLOWSOLVERPARAMETERS
_DCOPTIMIZERPARAMETERS.fields_by_name['double_limits'].message_type = toop__engine__interfaces_dot_messages_dot_protobuf__schema_dot_optimizer_dot_ac__dc__commons__pb2._DOUBLELIMITSSETPOINT
DESCRIPTOR.message_types_by_name['BatchedMEParameters'] = _BATCHEDMEPARAMETERS
DESCRIPTOR.message_types_by_name['TargetMetric'] = _TARGETMETRIC
DESCRIPTOR.message_types_by_name['LoadflowSolverParameters'] = _LOADFLOWSOLVERPARAMETERS
DESCRIPTOR.message_types_by_name['DCOptimizerParameters'] = _DCOPTIMIZERPARAMETERS
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

BatchedMEParameters = _reflection.GeneratedProtocolMessageType('BatchedMEParameters', (_message.Message,), {
  'DESCRIPTOR' : _BATCHEDMEPARAMETERS,
  '__module__' : 'toop_engine_interfaces.messages.protobuf_schema.optimizer.dc_optimizer_params_pb2'
  # @@protoc_insertion_point(class_scope:messages.optimizer.BatchedMEParameters)
  })
_sym_db.RegisterMessage(BatchedMEParameters)

TargetMetric = _reflection.GeneratedProtocolMessageType('TargetMetric', (_message.Message,), {
  'DESCRIPTOR' : _TARGETMETRIC,
  '__module__' : 'toop_engine_interfaces.messages.protobuf_schema.optimizer.dc_optimizer_params_pb2'
  # @@protoc_insertion_point(class_scope:messages.optimizer.TargetMetric)
  })
_sym_db.RegisterMessage(TargetMetric)

LoadflowSolverParameters = _reflection.GeneratedProtocolMessageType('LoadflowSolverParameters', (_message.Message,), {
  'DESCRIPTOR' : _LOADFLOWSOLVERPARAMETERS,
  '__module__' : 'toop_engine_interfaces.messages.protobuf_schema.optimizer.dc_optimizer_params_pb2'
  # @@protoc_insertion_point(class_scope:messages.optimizer.LoadflowSolverParameters)
  })
_sym_db.RegisterMessage(LoadflowSolverParameters)

DCOptimizerParameters = _reflection.GeneratedProtocolMessageType('DCOptimizerParameters', (_message.Message,), {
  'DESCRIPTOR' : _DCOPTIMIZERPARAMETERS,
  '__module__' : 'toop_engine_interfaces.messages.protobuf_schema.optimizer.dc_optimizer_params_pb2'
  # @@protoc_insertion_point(class_scope:messages.optimizer.DCOptimizerParameters)
  })
_sym_db.RegisterMessage(DCOptimizerParameters)


# @@protoc_insertion_point(module_scope)
