# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: toop_engine_interfaces/messages/protobuf_schema/optimizer/optimiser_commands.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from toop_engine_interfaces.messages.protobuf_schema.optimizer import ac_dc_commons_pb2 as toop__engine__interfaces_dot_messages_dot_protobuf__schema_dot_optimizer_dot_ac__dc__commons__pb2
from toop_engine_interfaces.messages.protobuf_schema.optimizer import ac_optimizer_params_pb2 as toop__engine__interfaces_dot_messages_dot_protobuf__schema_dot_optimizer_dot_ac__optimizer__params__pb2
from toop_engine_interfaces.messages.protobuf_schema.optimizer import dc_optimizer_params_pb2 as toop__engine__interfaces_dot_messages_dot_protobuf__schema_dot_optimizer_dot_dc__optimizer__params__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='toop_engine_interfaces/messages/protobuf_schema/optimizer/optimiser_commands.proto',
  package='messages.optimizer',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\nRtoop_engine_interfaces/messages/protobuf_schema/optimizer/optimiser_commands.proto\x12\x12messages.optimizer\x1aMtoop_engine_interfaces/messages/protobuf_schema/optimizer/ac_dc_commons.proto\x1aStoop_engine_interfaces/messages/protobuf_schema/optimizer/ac_optimizer_params.proto\x1aStoop_engine_interfaces/messages/protobuf_schema/optimizer/dc_optimizer_params.proto\"\xf7\x01\n\x18StartOptimizationCommand\x12\x14\n\x0cmessage_type\x18\x01 \x01(\t\x12<\n\tdc_params\x18\x02 \x01(\x0b\x32).messages.optimizer.DCOptimizerParameters\x12<\n\tac_params\x18\x03 \x01(\x0b\x32).messages.optimizer.ACOptimizerParameters\x12\x30\n\ngrid_files\x18\x04 \x03(\x0b\x32\x1c.messages.optimizer.GridFile\x12\x17\n\x0foptimization_id\x18\x05 \x01(\t\":\n\x0fShutdownCommand\x12\x14\n\x0cmessage_type\x18\x01 \x01(\t\x12\x11\n\texit_code\x18\x02 \x01(\x05\"\xba\x01\n\x07\x43ommand\x12J\n\x12start_optimization\x18\x01 \x01(\x0b\x32,.messages.optimizer.StartOptimizationCommandH\x00\x12\x37\n\x08shutdown\x18\x02 \x01(\x0b\x32#.messages.optimizer.ShutdownCommandH\x00\x12\x0c\n\x04uuid\x18\x03 \x01(\t\x12\x11\n\ttimestamp\x18\x04 \x01(\tB\t\n\x07\x63ommandb\x06proto3'
  ,
  dependencies=[toop__engine__interfaces_dot_messages_dot_protobuf__schema_dot_optimizer_dot_ac__dc__commons__pb2.DESCRIPTOR,toop__engine__interfaces_dot_messages_dot_protobuf__schema_dot_optimizer_dot_ac__optimizer__params__pb2.DESCRIPTOR,toop__engine__interfaces_dot_messages_dot_protobuf__schema_dot_optimizer_dot_dc__optimizer__params__pb2.DESCRIPTOR,])




_STARTOPTIMIZATIONCOMMAND = _descriptor.Descriptor(
  name='StartOptimizationCommand',
  full_name='messages.optimizer.StartOptimizationCommand',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='message_type', full_name='messages.optimizer.StartOptimizationCommand.message_type', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='dc_params', full_name='messages.optimizer.StartOptimizationCommand.dc_params', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='ac_params', full_name='messages.optimizer.StartOptimizationCommand.ac_params', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='grid_files', full_name='messages.optimizer.StartOptimizationCommand.grid_files', index=3,
      number=4, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='optimization_id', full_name='messages.optimizer.StartOptimizationCommand.optimization_id', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=356,
  serialized_end=603,
)


_SHUTDOWNCOMMAND = _descriptor.Descriptor(
  name='ShutdownCommand',
  full_name='messages.optimizer.ShutdownCommand',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='message_type', full_name='messages.optimizer.ShutdownCommand.message_type', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='exit_code', full_name='messages.optimizer.ShutdownCommand.exit_code', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=605,
  serialized_end=663,
)


_COMMAND = _descriptor.Descriptor(
  name='Command',
  full_name='messages.optimizer.Command',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='start_optimization', full_name='messages.optimizer.Command.start_optimization', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='shutdown', full_name='messages.optimizer.Command.shutdown', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='uuid', full_name='messages.optimizer.Command.uuid', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='timestamp', full_name='messages.optimizer.Command.timestamp', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='command', full_name='messages.optimizer.Command.command',
      index=0, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
  ],
  serialized_start=666,
  serialized_end=852,
)

_STARTOPTIMIZATIONCOMMAND.fields_by_name['dc_params'].message_type = toop__engine__interfaces_dot_messages_dot_protobuf__schema_dot_optimizer_dot_dc__optimizer__params__pb2._DCOPTIMIZERPARAMETERS
_STARTOPTIMIZATIONCOMMAND.fields_by_name['ac_params'].message_type = toop__engine__interfaces_dot_messages_dot_protobuf__schema_dot_optimizer_dot_ac__optimizer__params__pb2._ACOPTIMIZERPARAMETERS
_STARTOPTIMIZATIONCOMMAND.fields_by_name['grid_files'].message_type = toop__engine__interfaces_dot_messages_dot_protobuf__schema_dot_optimizer_dot_ac__dc__commons__pb2._GRIDFILE
_COMMAND.fields_by_name['start_optimization'].message_type = _STARTOPTIMIZATIONCOMMAND
_COMMAND.fields_by_name['shutdown'].message_type = _SHUTDOWNCOMMAND
_COMMAND.oneofs_by_name['command'].fields.append(
  _COMMAND.fields_by_name['start_optimization'])
_COMMAND.fields_by_name['start_optimization'].containing_oneof = _COMMAND.oneofs_by_name['command']
_COMMAND.oneofs_by_name['command'].fields.append(
  _COMMAND.fields_by_name['shutdown'])
_COMMAND.fields_by_name['shutdown'].containing_oneof = _COMMAND.oneofs_by_name['command']
DESCRIPTOR.message_types_by_name['StartOptimizationCommand'] = _STARTOPTIMIZATIONCOMMAND
DESCRIPTOR.message_types_by_name['ShutdownCommand'] = _SHUTDOWNCOMMAND
DESCRIPTOR.message_types_by_name['Command'] = _COMMAND
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

StartOptimizationCommand = _reflection.GeneratedProtocolMessageType('StartOptimizationCommand', (_message.Message,), {
  'DESCRIPTOR' : _STARTOPTIMIZATIONCOMMAND,
  '__module__' : 'toop_engine_interfaces.messages.protobuf_schema.optimizer.optimiser_commands_pb2'
  # @@protoc_insertion_point(class_scope:messages.optimizer.StartOptimizationCommand)
  })
_sym_db.RegisterMessage(StartOptimizationCommand)

ShutdownCommand = _reflection.GeneratedProtocolMessageType('ShutdownCommand', (_message.Message,), {
  'DESCRIPTOR' : _SHUTDOWNCOMMAND,
  '__module__' : 'toop_engine_interfaces.messages.protobuf_schema.optimizer.optimiser_commands_pb2'
  # @@protoc_insertion_point(class_scope:messages.optimizer.ShutdownCommand)
  })
_sym_db.RegisterMessage(ShutdownCommand)

Command = _reflection.GeneratedProtocolMessageType('Command', (_message.Message,), {
  'DESCRIPTOR' : _COMMAND,
  '__module__' : 'toop_engine_interfaces.messages.protobuf_schema.optimizer.optimiser_commands_pb2'
  # @@protoc_insertion_point(class_scope:messages.optimizer.Command)
  })
_sym_db.RegisterMessage(Command)


# @@protoc_insertion_point(module_scope)
