"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""
import builtins
import collections.abc
import google.protobuf.descriptor
import google.protobuf.internal.containers
import google.protobuf.message
import sys
import toop_engine_interfaces.messages.protobuf_schema.optimizer.ac_dc_commons_pb2
import toop_engine_interfaces.messages.protobuf_schema.optimizer.ac_optimizer_params_pb2
import toop_engine_interfaces.messages.protobuf_schema.optimizer.dc_optimizer_params_pb2

if sys.version_info >= (3, 8):
    import typing as typing_extensions
else:
    import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

class StartOptimizationCommand(google.protobuf.message.Message):
    """=====================================================
    COMMAND MESSAGES FROM BACKEND TO OPTIMIZER
    =====================================================

    Command with parameters for starting an optimization run.
    """

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    MESSAGE_TYPE_FIELD_NUMBER: builtins.int
    DC_PARAMS_FIELD_NUMBER: builtins.int
    AC_PARAMS_FIELD_NUMBER: builtins.int
    GRID_FILES_FIELD_NUMBER: builtins.int
    OPTIMIZATION_ID_FIELD_NUMBER: builtins.int
    message_type: builtins.str
    """The command type for deserialization. Always "start_optimization".
    Do not change this value.
    """
    @property
    def dc_params(self) -> toop_engine_interfaces.messages.protobuf_schema.optimizer.dc_optimizer_params_pb2.DCOptimizerParameters:
        """The parameters for the DC optimizer."""
    @property
    def ac_params(self) -> toop_engine_interfaces.messages.protobuf_schema.optimizer.ac_optimizer_params_pb2.ACOptimizerParameters:
        """The parameters for the AC optimizer."""
    @property
    def grid_files(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[toop_engine_interfaces.messages.protobuf_schema.optimizer.ac_dc_commons_pb2.GridFile]:
        """The grid files to load, where each GridFile represents one timestep.
        The grid files also include coupling information for the timesteps.
        NOTE: The first GridFile must be uncoupled ("coupling" == "none").
        """
    optimization_id: builtins.str
    """The ID of the optimization run.
    Used to identify the optimization run in the results.
    Should remain constant throughout the entire optimization run and
    should be equal to the Kafka event key.
    """
    def __init__(
        self,
        *,
        message_type: builtins.str = ...,
        dc_params: toop_engine_interfaces.messages.protobuf_schema.optimizer.dc_optimizer_params_pb2.DCOptimizerParameters | None = ...,
        ac_params: toop_engine_interfaces.messages.protobuf_schema.optimizer.ac_optimizer_params_pb2.ACOptimizerParameters | None = ...,
        grid_files: collections.abc.Iterable[toop_engine_interfaces.messages.protobuf_schema.optimizer.ac_dc_commons_pb2.GridFile] | None = ...,
        optimization_id: builtins.str = ...,
    ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["ac_params", b"ac_params", "dc_params", b"dc_params"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["ac_params", b"ac_params", "dc_params", b"dc_params", "grid_files", b"grid_files", "message_type", b"message_type", "optimization_id", b"optimization_id"]) -> None: ...

global___StartOptimizationCommand = StartOptimizationCommand

class ShutdownCommand(google.protobuf.message.Message):
    """=====================================================

    Command to shut down the worker.
    """

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    MESSAGE_TYPE_FIELD_NUMBER: builtins.int
    EXIT_CODE_FIELD_NUMBER: builtins.int
    message_type: builtins.str
    """The command type for deserialization. Always "shutdown".
    Do not change this value.
    """
    exit_code: builtins.int
    """The exit code to terminate the worker with."""
    def __init__(
        self,
        *,
        message_type: builtins.str = ...,
        exit_code: builtins.int = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["exit_code", b"exit_code", "message_type", b"message_type"]) -> None: ...

global___ShutdownCommand = ShutdownCommand

class Command(google.protobuf.message.Message):
    """=====================================================
    WRAPPER COMMAND MESSAGE
    =====================================================

    Base class for all commands to the optimizer.

    This acts as a discriminated union (`message_type` field)
    allowing different command variants to be sent through the same topic or RPC call.
    """

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    START_OPTIMIZATION_FIELD_NUMBER: builtins.int
    SHUTDOWN_FIELD_NUMBER: builtins.int
    UUID_FIELD_NUMBER: builtins.int
    TIMESTAMP_FIELD_NUMBER: builtins.int
    @property
    def start_optimization(self) -> global___StartOptimizationCommand: ...
    @property
    def shutdown(self) -> global___ShutdownCommand: ...
    uuid: builtins.str
    """A unique identifier for the command message,
    used to avoid duplicate processing on the optimizer side.
    """
    timestamp: builtins.str
    """When the command was sent (ISO 8601 string)."""
    def __init__(
        self,
        *,
        start_optimization: global___StartOptimizationCommand | None = ...,
        shutdown: global___ShutdownCommand | None = ...,
        uuid: builtins.str = ...,
        timestamp: builtins.str = ...,
    ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["command", b"command", "shutdown", b"shutdown", "start_optimization", b"start_optimization"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["command", b"command", "shutdown", b"shutdown", "start_optimization", b"start_optimization", "timestamp", b"timestamp", "uuid", b"uuid"]) -> None: ...
    def WhichOneof(self, oneof_group: typing_extensions.Literal["command", b"command"]) -> typing_extensions.Literal["start_optimization", "shutdown"] | None: ...

global___Command = Command
