# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: toop_engine_interfaces/messages/protobuf_schema/optimizer/optimiser_heartbeats.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='toop_engine_interfaces/messages/protobuf_schema/optimizer/optimiser_heartbeats.proto',
  package='messages.optimiser',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\nTtoop_engine_interfaces/messages/protobuf_schema/optimizer/optimiser_heartbeats.proto\x12\x12messages.optimiser\"M\n\x1cOptimizationStartedHeartbeat\x12\x14\n\x0cmessage_type\x18\x01 \x01(\t\x12\x17\n\x0foptimization_id\x18\x02 \x01(\t\"\xbe\x01\n\x1aOptimizationStatsHeartbeat\x12\x14\n\x0cmessage_type\x18\x01 \x01(\t\x12\x17\n\x0foptimization_id\x18\x02 \x01(\t\x12\x11\n\twall_time\x18\x03 \x01(\x01\x12\x11\n\titeration\x18\x04 \x01(\x04\x12#\n\x1bnum_branch_topologies_tried\x18\x05 \x01(\x04\x12&\n\x1enum_injection_topologies_tried\x18\x06 \x01(\x04\"%\n\rIdleHeartbeat\x12\x14\n\x0cmessage_type\x18\x01 \x01(\t\"[\n\nLogMessage\x12\x14\n\x0cmessage_type\x18\x01 \x01(\t\x12\x17\n\x0foptimization_id\x18\x02 \x01(\t\x12\x0f\n\x07message\x18\x03 \x01(\t\x12\r\n\x05\x65rror\x18\x04 \x01(\x08\"\x9d\x02\n\x0eHeartbeatUnion\x12\x31\n\x04idle\x18\x01 \x01(\x0b\x32!.messages.optimiser.IdleHeartbeatH\x00\x12-\n\x03log\x18\x02 \x01(\x0b\x32\x1e.messages.optimiser.LogMessageH\x00\x12L\n\x12optimization_stats\x18\x03 \x01(\x0b\x32..messages.optimiser.OptimizationStatsHeartbeatH\x00\x12P\n\x14optimization_started\x18\x04 \x01(\x0b\x32\x30.messages.optimiser.OptimizationStartedHeartbeatH\x00\x42\t\n\x07message\"\x8e\x01\n\tHeartbeat\x12\x33\n\x07message\x18\x01 \x01(\x0b\x32\".messages.optimiser.HeartbeatUnion\x12\x16\n\x0eoptimizer_type\x18\x02 \x01(\t\x12\x13\n\x0binstance_id\x18\x03 \x01(\t\x12\x11\n\ttimestamp\x18\x04 \x01(\t\x12\x0c\n\x04uuid\x18\x05 \x01(\t\"0\n\x0cHeartbeatAck\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t2d\n\x10HeartbeatService\x12P\n\rSendHeartbeat\x12\x1d.messages.optimiser.Heartbeat\x1a .messages.optimiser.HeartbeatAckb\x06proto3'
)




_OPTIMIZATIONSTARTEDHEARTBEAT = _descriptor.Descriptor(
  name='OptimizationStartedHeartbeat',
  full_name='messages.optimiser.OptimizationStartedHeartbeat',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='message_type', full_name='messages.optimiser.OptimizationStartedHeartbeat.message_type', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='optimization_id', full_name='messages.optimiser.OptimizationStartedHeartbeat.optimization_id', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=108,
  serialized_end=185,
)


_OPTIMIZATIONSTATSHEARTBEAT = _descriptor.Descriptor(
  name='OptimizationStatsHeartbeat',
  full_name='messages.optimiser.OptimizationStatsHeartbeat',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='message_type', full_name='messages.optimiser.OptimizationStatsHeartbeat.message_type', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='optimization_id', full_name='messages.optimiser.OptimizationStatsHeartbeat.optimization_id', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='wall_time', full_name='messages.optimiser.OptimizationStatsHeartbeat.wall_time', index=2,
      number=3, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='iteration', full_name='messages.optimiser.OptimizationStatsHeartbeat.iteration', index=3,
      number=4, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='num_branch_topologies_tried', full_name='messages.optimiser.OptimizationStatsHeartbeat.num_branch_topologies_tried', index=4,
      number=5, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='num_injection_topologies_tried', full_name='messages.optimiser.OptimizationStatsHeartbeat.num_injection_topologies_tried', index=5,
      number=6, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=188,
  serialized_end=378,
)


_IDLEHEARTBEAT = _descriptor.Descriptor(
  name='IdleHeartbeat',
  full_name='messages.optimiser.IdleHeartbeat',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='message_type', full_name='messages.optimiser.IdleHeartbeat.message_type', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=380,
  serialized_end=417,
)


_LOGMESSAGE = _descriptor.Descriptor(
  name='LogMessage',
  full_name='messages.optimiser.LogMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='message_type', full_name='messages.optimiser.LogMessage.message_type', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='optimization_id', full_name='messages.optimiser.LogMessage.optimization_id', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='message', full_name='messages.optimiser.LogMessage.message', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='error', full_name='messages.optimiser.LogMessage.error', index=3,
      number=4, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=419,
  serialized_end=510,
)


_HEARTBEATUNION = _descriptor.Descriptor(
  name='HeartbeatUnion',
  full_name='messages.optimiser.HeartbeatUnion',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='idle', full_name='messages.optimiser.HeartbeatUnion.idle', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='log', full_name='messages.optimiser.HeartbeatUnion.log', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='optimization_stats', full_name='messages.optimiser.HeartbeatUnion.optimization_stats', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='optimization_started', full_name='messages.optimiser.HeartbeatUnion.optimization_started', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='message', full_name='messages.optimiser.HeartbeatUnion.message',
      index=0, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
  ],
  serialized_start=513,
  serialized_end=798,
)


_HEARTBEAT = _descriptor.Descriptor(
  name='Heartbeat',
  full_name='messages.optimiser.Heartbeat',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='message', full_name='messages.optimiser.Heartbeat.message', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='optimizer_type', full_name='messages.optimiser.Heartbeat.optimizer_type', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='instance_id', full_name='messages.optimiser.Heartbeat.instance_id', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='timestamp', full_name='messages.optimiser.Heartbeat.timestamp', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='uuid', full_name='messages.optimiser.Heartbeat.uuid', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=801,
  serialized_end=943,
)


_HEARTBEATACK = _descriptor.Descriptor(
  name='HeartbeatAck',
  full_name='messages.optimiser.HeartbeatAck',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='success', full_name='messages.optimiser.HeartbeatAck.success', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='message', full_name='messages.optimiser.HeartbeatAck.message', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=945,
  serialized_end=993,
)

_HEARTBEATUNION.fields_by_name['idle'].message_type = _IDLEHEARTBEAT
_HEARTBEATUNION.fields_by_name['log'].message_type = _LOGMESSAGE
_HEARTBEATUNION.fields_by_name['optimization_stats'].message_type = _OPTIMIZATIONSTATSHEARTBEAT
_HEARTBEATUNION.fields_by_name['optimization_started'].message_type = _OPTIMIZATIONSTARTEDHEARTBEAT
_HEARTBEATUNION.oneofs_by_name['message'].fields.append(
  _HEARTBEATUNION.fields_by_name['idle'])
_HEARTBEATUNION.fields_by_name['idle'].containing_oneof = _HEARTBEATUNION.oneofs_by_name['message']
_HEARTBEATUNION.oneofs_by_name['message'].fields.append(
  _HEARTBEATUNION.fields_by_name['log'])
_HEARTBEATUNION.fields_by_name['log'].containing_oneof = _HEARTBEATUNION.oneofs_by_name['message']
_HEARTBEATUNION.oneofs_by_name['message'].fields.append(
  _HEARTBEATUNION.fields_by_name['optimization_stats'])
_HEARTBEATUNION.fields_by_name['optimization_stats'].containing_oneof = _HEARTBEATUNION.oneofs_by_name['message']
_HEARTBEATUNION.oneofs_by_name['message'].fields.append(
  _HEARTBEATUNION.fields_by_name['optimization_started'])
_HEARTBEATUNION.fields_by_name['optimization_started'].containing_oneof = _HEARTBEATUNION.oneofs_by_name['message']
_HEARTBEAT.fields_by_name['message'].message_type = _HEARTBEATUNION
DESCRIPTOR.message_types_by_name['OptimizationStartedHeartbeat'] = _OPTIMIZATIONSTARTEDHEARTBEAT
DESCRIPTOR.message_types_by_name['OptimizationStatsHeartbeat'] = _OPTIMIZATIONSTATSHEARTBEAT
DESCRIPTOR.message_types_by_name['IdleHeartbeat'] = _IDLEHEARTBEAT
DESCRIPTOR.message_types_by_name['LogMessage'] = _LOGMESSAGE
DESCRIPTOR.message_types_by_name['HeartbeatUnion'] = _HEARTBEATUNION
DESCRIPTOR.message_types_by_name['Heartbeat'] = _HEARTBEAT
DESCRIPTOR.message_types_by_name['HeartbeatAck'] = _HEARTBEATACK
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

OptimizationStartedHeartbeat = _reflection.GeneratedProtocolMessageType('OptimizationStartedHeartbeat', (_message.Message,), {
  'DESCRIPTOR' : _OPTIMIZATIONSTARTEDHEARTBEAT,
  '__module__' : 'toop_engine_interfaces.messages.protobuf_schema.optimizer.optimiser_heartbeats_pb2'
  # @@protoc_insertion_point(class_scope:messages.optimiser.OptimizationStartedHeartbeat)
  })
_sym_db.RegisterMessage(OptimizationStartedHeartbeat)

OptimizationStatsHeartbeat = _reflection.GeneratedProtocolMessageType('OptimizationStatsHeartbeat', (_message.Message,), {
  'DESCRIPTOR' : _OPTIMIZATIONSTATSHEARTBEAT,
  '__module__' : 'toop_engine_interfaces.messages.protobuf_schema.optimizer.optimiser_heartbeats_pb2'
  # @@protoc_insertion_point(class_scope:messages.optimiser.OptimizationStatsHeartbeat)
  })
_sym_db.RegisterMessage(OptimizationStatsHeartbeat)

IdleHeartbeat = _reflection.GeneratedProtocolMessageType('IdleHeartbeat', (_message.Message,), {
  'DESCRIPTOR' : _IDLEHEARTBEAT,
  '__module__' : 'toop_engine_interfaces.messages.protobuf_schema.optimizer.optimiser_heartbeats_pb2'
  # @@protoc_insertion_point(class_scope:messages.optimiser.IdleHeartbeat)
  })
_sym_db.RegisterMessage(IdleHeartbeat)

LogMessage = _reflection.GeneratedProtocolMessageType('LogMessage', (_message.Message,), {
  'DESCRIPTOR' : _LOGMESSAGE,
  '__module__' : 'toop_engine_interfaces.messages.protobuf_schema.optimizer.optimiser_heartbeats_pb2'
  # @@protoc_insertion_point(class_scope:messages.optimiser.LogMessage)
  })
_sym_db.RegisterMessage(LogMessage)

HeartbeatUnion = _reflection.GeneratedProtocolMessageType('HeartbeatUnion', (_message.Message,), {
  'DESCRIPTOR' : _HEARTBEATUNION,
  '__module__' : 'toop_engine_interfaces.messages.protobuf_schema.optimizer.optimiser_heartbeats_pb2'
  # @@protoc_insertion_point(class_scope:messages.optimiser.HeartbeatUnion)
  })
_sym_db.RegisterMessage(HeartbeatUnion)

Heartbeat = _reflection.GeneratedProtocolMessageType('Heartbeat', (_message.Message,), {
  'DESCRIPTOR' : _HEARTBEAT,
  '__module__' : 'toop_engine_interfaces.messages.protobuf_schema.optimizer.optimiser_heartbeats_pb2'
  # @@protoc_insertion_point(class_scope:messages.optimiser.Heartbeat)
  })
_sym_db.RegisterMessage(Heartbeat)

HeartbeatAck = _reflection.GeneratedProtocolMessageType('HeartbeatAck', (_message.Message,), {
  'DESCRIPTOR' : _HEARTBEATACK,
  '__module__' : 'toop_engine_interfaces.messages.protobuf_schema.optimizer.optimiser_heartbeats_pb2'
  # @@protoc_insertion_point(class_scope:messages.optimiser.HeartbeatAck)
  })
_sym_db.RegisterMessage(HeartbeatAck)



_HEARTBEATSERVICE = _descriptor.ServiceDescriptor(
  name='HeartbeatService',
  full_name='messages.optimiser.HeartbeatService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=995,
  serialized_end=1095,
  methods=[
  _descriptor.MethodDescriptor(
    name='SendHeartbeat',
    full_name='messages.optimiser.HeartbeatService.SendHeartbeat',
    index=0,
    containing_service=None,
    input_type=_HEARTBEAT,
    output_type=_HEARTBEATACK,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_HEARTBEATSERVICE)

DESCRIPTOR.services_by_name['HeartbeatService'] = _HEARTBEATSERVICE

# @@protoc_insertion_point(module_scope)
