"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""
import builtins
import google.protobuf.descriptor
import google.protobuf.message
import sys

if sys.version_info >= (3, 8):
    import typing as typing_extensions
else:
    import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

class OptimizationStartedHeartbeat(google.protobuf.message.Message):
    """=====================================================
    OPTIMIZATION HEARTBEAT MESSAGES
    =====================================================

    A message sent by the optimizer when it starts.
    """

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    MESSAGE_TYPE_FIELD_NUMBER: builtins.int
    OPTIMIZATION_ID_FIELD_NUMBER: builtins.int
    message_type: builtins.str
    """The message type (always "optimization_started"). Don't change this."""
    optimization_id: builtins.str
    """The ID of the optimization."""
    def __init__(
        self,
        *,
        message_type: builtins.str = ...,
        optimization_id: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["message_type", b"message_type", "optimization_id", b"optimization_id"]) -> None: ...

global___OptimizationStartedHeartbeat = OptimizationStartedHeartbeat

class OptimizationStatsHeartbeat(google.protobuf.message.Message):
    """=====================================================
    OPTIMIZATION STATISTICS HEARTBEAT
    =====================================================

    Optimization statistics to track the progress of the optimizer.
    """

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    MESSAGE_TYPE_FIELD_NUMBER: builtins.int
    OPTIMIZATION_ID_FIELD_NUMBER: builtins.int
    WALL_TIME_FIELD_NUMBER: builtins.int
    ITERATION_FIELD_NUMBER: builtins.int
    NUM_BRANCH_TOPOLOGIES_TRIED_FIELD_NUMBER: builtins.int
    NUM_INJECTION_TOPOLOGIES_TRIED_FIELD_NUMBER: builtins.int
    message_type: builtins.str
    """The message type (always "optimization_stats"). Don't change this."""
    optimization_id: builtins.str
    """The ID of the optimization."""
    wall_time: builtins.float
    """The number of seconds since the start of the optimization."""
    iteration: builtins.int
    """The current iteration number."""
    num_branch_topologies_tried: builtins.int
    """The number of branch topologies tried so far."""
    num_injection_topologies_tried: builtins.int
    """The number of injection topologies tried so far."""
    def __init__(
        self,
        *,
        message_type: builtins.str = ...,
        optimization_id: builtins.str = ...,
        wall_time: builtins.float = ...,
        iteration: builtins.int = ...,
        num_branch_topologies_tried: builtins.int = ...,
        num_injection_topologies_tried: builtins.int = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["iteration", b"iteration", "message_type", b"message_type", "num_branch_topologies_tried", b"num_branch_topologies_tried", "num_injection_topologies_tried", b"num_injection_topologies_tried", "optimization_id", b"optimization_id", "wall_time", b"wall_time"]) -> None: ...

global___OptimizationStatsHeartbeat = OptimizationStatsHeartbeat

class IdleHeartbeat(google.protobuf.message.Message):
    """=====================================================
    IDLE HEARTBEAT
    =====================================================

    A heartbeat that is sent by the optimizer when idle.
    """

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    MESSAGE_TYPE_FIELD_NUMBER: builtins.int
    message_type: builtins.str
    """The message type (always "idle"). Don't change this."""
    def __init__(
        self,
        *,
        message_type: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["message_type", b"message_type"]) -> None: ...

global___IdleHeartbeat = IdleHeartbeat

class LogMessage(google.protobuf.message.Message):
    """=====================================================
    LOG MESSAGE
    =====================================================

    A log message that is sent by the optimizer to the master.
    """

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    MESSAGE_TYPE_FIELD_NUMBER: builtins.int
    OPTIMIZATION_ID_FIELD_NUMBER: builtins.int
    MESSAGE_FIELD_NUMBER: builtins.int
    ERROR_FIELD_NUMBER: builtins.int
    message_type: builtins.str
    """The message type (always "log"). Don't change this."""
    optimization_id: builtins.str
    """The ID of the optimization this message belongs to."""
    message: builtins.str
    """The message content to log."""
    error: builtins.bool
    """Whether this log entry represents an error."""
    def __init__(
        self,
        *,
        message_type: builtins.str = ...,
        optimization_id: builtins.str = ...,
        message: builtins.str = ...,
        error: builtins.bool = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["error", b"error", "message", b"message", "message_type", b"message_type", "optimization_id", b"optimization_id"]) -> None: ...

global___LogMessage = LogMessage

class HeartbeatUnion(google.protobuf.message.Message):
    """=====================================================
    HEARTBEAT WRAPPER (UNION TYPE)
    =====================================================

    The union of all possible heartbeat message types.
    Used to distinguish message content by type.
    """

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    IDLE_FIELD_NUMBER: builtins.int
    LOG_FIELD_NUMBER: builtins.int
    OPTIMIZATION_STATS_FIELD_NUMBER: builtins.int
    OPTIMIZATION_STARTED_FIELD_NUMBER: builtins.int
    @property
    def idle(self) -> global___IdleHeartbeat: ...
    @property
    def log(self) -> global___LogMessage: ...
    @property
    def optimization_stats(self) -> global___OptimizationStatsHeartbeat: ...
    @property
    def optimization_started(self) -> global___OptimizationStartedHeartbeat: ...
    def __init__(
        self,
        *,
        idle: global___IdleHeartbeat | None = ...,
        log: global___LogMessage | None = ...,
        optimization_stats: global___OptimizationStatsHeartbeat | None = ...,
        optimization_started: global___OptimizationStartedHeartbeat | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["idle", b"idle", "log", b"log", "message", b"message", "optimization_started", b"optimization_started", "optimization_stats", b"optimization_stats"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["idle", b"idle", "log", b"log", "message", b"message", "optimization_started", b"optimization_started", "optimization_stats", b"optimization_stats"]) -> None: ...
    def WhichOneof(self, oneof_group: typing_extensions.Literal["message", b"message"]) -> typing_extensions.Literal["idle", "log", "optimization_stats", "optimization_started"] | None: ...

global___HeartbeatUnion = HeartbeatUnion

class Heartbeat(google.protobuf.message.Message):
    """=====================================================
    HEARTBEAT MESSAGE ENVELOPE
    =====================================================

    The outer heartbeat message sent by an optimizer instance.
    """

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    MESSAGE_FIELD_NUMBER: builtins.int
    OPTIMIZER_TYPE_FIELD_NUMBER: builtins.int
    INSTANCE_ID_FIELD_NUMBER: builtins.int
    TIMESTAMP_FIELD_NUMBER: builtins.int
    UUID_FIELD_NUMBER: builtins.int
    @property
    def message(self) -> global___HeartbeatUnion:
        """The actual heartbeat payload. Discriminated by message_type."""
    optimizer_type: builtins.str
    """Which optimizer has sent the heartbeat."""
    instance_id: builtins.str
    """The instance ID of the optimizer."""
    timestamp: builtins.str
    """When the heartbeat was sent (ISO 8601 format recommended)."""
    uuid: builtins.str
    """A unique identifier for this heartbeat message.
    Used to avoid duplicates during processing.
    """
    def __init__(
        self,
        *,
        message: global___HeartbeatUnion | None = ...,
        optimizer_type: builtins.str = ...,
        instance_id: builtins.str = ...,
        timestamp: builtins.str = ...,
        uuid: builtins.str = ...,
    ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["message", b"message"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["instance_id", b"instance_id", "message", b"message", "optimizer_type", b"optimizer_type", "timestamp", b"timestamp", "uuid", b"uuid"]) -> None: ...

global___Heartbeat = Heartbeat

class HeartbeatAck(google.protobuf.message.Message):
    """Acknowledgment for a received heartbeat."""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    SUCCESS_FIELD_NUMBER: builtins.int
    MESSAGE_FIELD_NUMBER: builtins.int
    success: builtins.bool
    """Whether the heartbeat was successfully processed."""
    message: builtins.str
    """Optional status or error message."""
    def __init__(
        self,
        *,
        success: builtins.bool = ...,
        message: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["message", b"message", "success", b"success"]) -> None: ...

global___HeartbeatAck = HeartbeatAck
