# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: toop_engine_interfaces/messages/protobuf_schema/preprocess/preprocess_heartbeats.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database

# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor.FileDescriptor(
    name="toop_engine_interfaces/messages/protobuf_schema/preprocess/preprocess_heartbeats.proto",
    package="messages.preprocessing",
    syntax="proto3",
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
    serialized_pb=b'\nVtoop_engine_interfaces/messages/protobuf_schema/preprocess/preprocess_heartbeats.proto\x12\x16messages.preprocessing"^\n\x14PreprocessStatusInfo\x12\x15\n\rpreprocess_id\x18\x01 \x01(\t\x12\x0f\n\x07runtime\x18\x02 \x01(\x01\x12\r\n\x05stage\x18\x03 \x01(\t\x12\x0f\n\x07message\x18\x04 \x01(\t"\x9c\x01\n\x13PreprocessHeartbeat\x12\x0c\n\x04idle\x18\x01 \x01(\x08\x12\x41\n\x0bstatus_info\x18\x02 \x01(\x0b\x32,.messages.preprocessing.PreprocessStatusInfo\x12\x13\n\x0binstance_id\x18\x03 \x01(\t\x12\x11\n\ttimestamp\x18\x04 \x01(\t\x12\x0c\n\x04uuid\x18\x05 \x01(\tb\x06proto3',
)


_PREPROCESSSTATUSINFO = _descriptor.Descriptor(
    name="PreprocessStatusInfo",
    full_name="messages.preprocessing.PreprocessStatusInfo",
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    create_key=_descriptor._internal_create_key,
    fields=[
        _descriptor.FieldDescriptor(
            name="preprocess_id",
            full_name="messages.preprocessing.PreprocessStatusInfo.preprocess_id",
            index=0,
            number=1,
            type=9,
            cpp_type=9,
            label=1,
            has_default_value=False,
            default_value=b"".decode("utf-8"),
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
            create_key=_descriptor._internal_create_key,
        ),
        _descriptor.FieldDescriptor(
            name="runtime",
            full_name="messages.preprocessing.PreprocessStatusInfo.runtime",
            index=1,
            number=2,
            type=1,
            cpp_type=5,
            label=1,
            has_default_value=False,
            default_value=float(0),
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
            create_key=_descriptor._internal_create_key,
        ),
        _descriptor.FieldDescriptor(
            name="stage",
            full_name="messages.preprocessing.PreprocessStatusInfo.stage",
            index=2,
            number=3,
            type=9,
            cpp_type=9,
            label=1,
            has_default_value=False,
            default_value=b"".decode("utf-8"),
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
            create_key=_descriptor._internal_create_key,
        ),
        _descriptor.FieldDescriptor(
            name="message",
            full_name="messages.preprocessing.PreprocessStatusInfo.message",
            index=3,
            number=4,
            type=9,
            cpp_type=9,
            label=1,
            has_default_value=False,
            default_value=b"".decode("utf-8"),
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
            create_key=_descriptor._internal_create_key,
        ),
    ],
    extensions=[],
    nested_types=[],
    enum_types=[],
    serialized_options=None,
    is_extendable=False,
    syntax="proto3",
    extension_ranges=[],
    oneofs=[],
    serialized_start=114,
    serialized_end=208,
)


_PREPROCESSHEARTBEAT = _descriptor.Descriptor(
    name="PreprocessHeartbeat",
    full_name="messages.preprocessing.PreprocessHeartbeat",
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    create_key=_descriptor._internal_create_key,
    fields=[
        _descriptor.FieldDescriptor(
            name="idle",
            full_name="messages.preprocessing.PreprocessHeartbeat.idle",
            index=0,
            number=1,
            type=8,
            cpp_type=7,
            label=1,
            has_default_value=False,
            default_value=False,
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
            create_key=_descriptor._internal_create_key,
        ),
        _descriptor.FieldDescriptor(
            name="status_info",
            full_name="messages.preprocessing.PreprocessHeartbeat.status_info",
            index=1,
            number=2,
            type=11,
            cpp_type=10,
            label=1,
            has_default_value=False,
            default_value=None,
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
            create_key=_descriptor._internal_create_key,
        ),
        _descriptor.FieldDescriptor(
            name="instance_id",
            full_name="messages.preprocessing.PreprocessHeartbeat.instance_id",
            index=2,
            number=3,
            type=9,
            cpp_type=9,
            label=1,
            has_default_value=False,
            default_value=b"".decode("utf-8"),
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
            create_key=_descriptor._internal_create_key,
        ),
        _descriptor.FieldDescriptor(
            name="timestamp",
            full_name="messages.preprocessing.PreprocessHeartbeat.timestamp",
            index=3,
            number=4,
            type=9,
            cpp_type=9,
            label=1,
            has_default_value=False,
            default_value=b"".decode("utf-8"),
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
            create_key=_descriptor._internal_create_key,
        ),
        _descriptor.FieldDescriptor(
            name="uuid",
            full_name="messages.preprocessing.PreprocessHeartbeat.uuid",
            index=4,
            number=5,
            type=9,
            cpp_type=9,
            label=1,
            has_default_value=False,
            default_value=b"".decode("utf-8"),
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
            create_key=_descriptor._internal_create_key,
        ),
    ],
    extensions=[],
    nested_types=[],
    enum_types=[],
    serialized_options=None,
    is_extendable=False,
    syntax="proto3",
    extension_ranges=[],
    oneofs=[],
    serialized_start=211,
    serialized_end=367,
)

_PREPROCESSHEARTBEAT.fields_by_name["status_info"].message_type = _PREPROCESSSTATUSINFO
DESCRIPTOR.message_types_by_name["PreprocessStatusInfo"] = _PREPROCESSSTATUSINFO
DESCRIPTOR.message_types_by_name["PreprocessHeartbeat"] = _PREPROCESSHEARTBEAT
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

PreprocessStatusInfo = _reflection.GeneratedProtocolMessageType(
    "PreprocessStatusInfo",
    (_message.Message,),
    {
        "DESCRIPTOR": _PREPROCESSSTATUSINFO,
        "__module__": "toop_engine_interfaces.messages.protobuf_schema.preprocess.preprocess_heartbeats_pb2",
        # @@protoc_insertion_point(class_scope:messages.preprocessing.PreprocessStatusInfo)
    },
)
_sym_db.RegisterMessage(PreprocessStatusInfo)

PreprocessHeartbeat = _reflection.GeneratedProtocolMessageType(
    "PreprocessHeartbeat",
    (_message.Message,),
    {
        "DESCRIPTOR": _PREPROCESSHEARTBEAT,
        "__module__": "toop_engine_interfaces.messages.protobuf_schema.preprocess.preprocess_heartbeats_pb2",
        # @@protoc_insertion_point(class_scope:messages.preprocessing.PreprocessHeartbeat)
    },
)
_sym_db.RegisterMessage(PreprocessHeartbeat)


# @@protoc_insertion_point(module_scope)
