"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""
import builtins
import google.protobuf.descriptor
import google.protobuf.message
import sys

if sys.version_info >= (3, 8):
    import typing as typing_extensions
else:
    import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

class PreprocessStatusInfo(google.protobuf.message.Message):
    """Represents an ongoing preprocessing action."""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    PREPROCESS_ID_FIELD_NUMBER: builtins.int
    RUNTIME_FIELD_NUMBER: builtins.int
    STAGE_FIELD_NUMBER: builtins.int
    MESSAGE_FIELD_NUMBER: builtins.int
    preprocess_id: builtins.str
    """ID of the preprocess job"""
    runtime: builtins.float
    """Time since start (seconds)"""
    stage: builtins.str
    """Current stage"""
    message: builtins.str
    """Optional message"""
    def __init__(
        self,
        *,
        preprocess_id: builtins.str = ...,
        runtime: builtins.float = ...,
        stage: builtins.str = ...,
        message: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["message", b"message", "preprocess_id", b"preprocess_id", "runtime", b"runtime", "stage", b"stage"]) -> None: ...

global___PreprocessStatusInfo = PreprocessStatusInfo

class PreprocessHeartbeat(google.protobuf.message.Message):
    """The heartbeat message from a preprocessing worker."""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    IDLE_FIELD_NUMBER: builtins.int
    STATUS_INFO_FIELD_NUMBER: builtins.int
    INSTANCE_ID_FIELD_NUMBER: builtins.int
    TIMESTAMP_FIELD_NUMBER: builtins.int
    UUID_FIELD_NUMBER: builtins.int
    idle: builtins.bool
    """Whether the worker is idle"""
    @property
    def status_info(self) -> global___PreprocessStatusInfo:
        """Status update if not idle"""
    instance_id: builtins.str
    """Worker instance ID"""
    timestamp: builtins.str
    """When the heartbeat was sent"""
    uuid: builtins.str
    """Unique ID to avoid duplicates"""
    def __init__(
        self,
        *,
        idle: builtins.bool = ...,
        status_info: global___PreprocessStatusInfo | None = ...,
        instance_id: builtins.str = ...,
        timestamp: builtins.str = ...,
        uuid: builtins.str = ...,
    ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["status_info", b"status_info"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["idle", b"idle", "instance_id", b"instance_id", "status_info", b"status_info", "timestamp", b"timestamp", "uuid", b"uuid"]) -> None: ...

global___PreprocessHeartbeat = PreprocessHeartbeat
