"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""
import builtins
import collections.abc
import google.protobuf.descriptor
import google.protobuf.internal.containers
import google.protobuf.message
import google.protobuf.timestamp_pb2
import sys

if sys.version_info >= (3, 8):
    import typing as typing_extensions
else:
    import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

class LimitAdjustmentParameters(google.protobuf.message.Message):
    """*
    Parameters for the adjustment of limits of special branches.

    The new operational limits will be created like this:
    1) Compute AC Loadflow
    2) new_limit = current_flow * n_0_factor (or n_1_factor)
    3) If new_limit > min_increase (=old_limit * n_0_min_increase)
         new_limit = min_increase
    4) If new_limit > old_limit
         new_limit = old_limit
    """

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    N_0_FACTOR_FIELD_NUMBER: builtins.int
    N_1_FACTOR_FIELD_NUMBER: builtins.int
    N_0_MIN_INCREASE_FIELD_NUMBER: builtins.int
    N_1_MIN_INCREASE_FIELD_NUMBER: builtins.int
    n_0_factor: builtins.float
    """The factor for the N-0 current limit. Default is 1.2."""
    n_1_factor: builtins.float
    """The factor for the N-1 current limit. Default is 1.4."""
    n_0_min_increase: builtins.float
    """The minimal allowed load increase in percent for the n-0 case.
    This value multiplied with the current limit gives a lower border for the new limit.
    This ensures that lines that are currently barely loaded can be used at all.
    Default is 5%.
    """
    n_1_min_increase: builtins.float
    """The minimal allowed load increase in percent for the n-1 case.
    This value multiplied with the current limit gives a lower border for the new limit.
    This ensures that lines that are currently barely loaded can be used at all.
    Default is 5%.
    """
    def __init__(
        self,
        *,
        n_0_factor: builtins.float = ...,
        n_1_factor: builtins.float = ...,
        n_0_min_increase: builtins.float = ...,
        n_1_min_increase: builtins.float = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["n_0_factor", b"n_0_factor", "n_0_min_increase", b"n_0_min_increase", "n_1_factor", b"n_1_factor", "n_1_min_increase", b"n_1_min_increase"]) -> None: ...

global___LimitAdjustmentParameters = LimitAdjustmentParameters

class AreaSettings(google.protobuf.message.Message):
    """---------------------------
    AreaSettings
    ---------------------------
    """

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    CONTROL_AREA_FIELD_NUMBER: builtins.int
    VIEW_AREA_FIELD_NUMBER: builtins.int
    NMINUS1_AREA_FIELD_NUMBER: builtins.int
    CUTOFF_VOLTAGE_FIELD_NUMBER: builtins.int
    DSO_TRAFO_FACTORS_FIELD_NUMBER: builtins.int
    DSO_TRAFO_WEIGHT_FIELD_NUMBER: builtins.int
    BORDER_LINE_FACTORS_FIELD_NUMBER: builtins.int
    BORDER_LINE_WEIGHT_FIELD_NUMBER: builtins.int
    @property
    def control_area(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.str]: ...
    @property
    def view_area(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.str]: ...
    @property
    def nminus1_area(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.str]: ...
    cutoff_voltage: builtins.int
    @property
    def dso_trafo_factors(self) -> global___LimitAdjustmentParameters: ...
    dso_trafo_weight: builtins.float
    @property
    def border_line_factors(self) -> global___LimitAdjustmentParameters: ...
    border_line_weight: builtins.float
    def __init__(
        self,
        *,
        control_area: collections.abc.Iterable[builtins.str] | None = ...,
        view_area: collections.abc.Iterable[builtins.str] | None = ...,
        nminus1_area: collections.abc.Iterable[builtins.str] | None = ...,
        cutoff_voltage: builtins.int = ...,
        dso_trafo_factors: global___LimitAdjustmentParameters | None = ...,
        dso_trafo_weight: builtins.float = ...,
        border_line_factors: global___LimitAdjustmentParameters | None = ...,
        border_line_weight: builtins.float = ...,
    ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["border_line_factors", b"border_line_factors", "dso_trafo_factors", b"dso_trafo_factors"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["border_line_factors", b"border_line_factors", "border_line_weight", b"border_line_weight", "control_area", b"control_area", "cutoff_voltage", b"cutoff_voltage", "dso_trafo_factors", b"dso_trafo_factors", "dso_trafo_weight", b"dso_trafo_weight", "nminus1_area", b"nminus1_area", "view_area", b"view_area"]) -> None: ...

global___AreaSettings = AreaSettings

class BaseImporterParameters(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    AREA_SETTINGS_FIELD_NUMBER: builtins.int
    DATA_FOLDER_FIELD_NUMBER: builtins.int
    GRID_MODEL_FILE_FIELD_NUMBER: builtins.int
    DATA_TYPE_FIELD_NUMBER: builtins.int
    WHITE_LIST_FILE_FIELD_NUMBER: builtins.int
    BLACK_LIST_FILE_FIELD_NUMBER: builtins.int
    IGNORE_LIST_FILE_FIELD_NUMBER: builtins.int
    INGRESS_ID_FIELD_NUMBER: builtins.int
    CONTINGENCY_LIST_FILE_FIELD_NUMBER: builtins.int
    SCHEMA_FORMAT_FIELD_NUMBER: builtins.int
    @property
    def area_settings(self) -> global___AreaSettings: ...
    data_folder: builtins.str
    grid_model_file: builtins.str
    data_type: builtins.str
    white_list_file: builtins.str
    black_list_file: builtins.str
    ignore_list_file: builtins.str
    ingress_id: builtins.str
    contingency_list_file: builtins.str
    schema_format: builtins.str
    def __init__(
        self,
        *,
        area_settings: global___AreaSettings | None = ...,
        data_folder: builtins.str = ...,
        grid_model_file: builtins.str = ...,
        data_type: builtins.str = ...,
        white_list_file: builtins.str = ...,
        black_list_file: builtins.str = ...,
        ignore_list_file: builtins.str = ...,
        ingress_id: builtins.str = ...,
        contingency_list_file: builtins.str = ...,
        schema_format: builtins.str = ...,
    ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["area_settings", b"area_settings"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["area_settings", b"area_settings", "black_list_file", b"black_list_file", "contingency_list_file", b"contingency_list_file", "data_folder", b"data_folder", "data_type", b"data_type", "grid_model_file", b"grid_model_file", "ignore_list_file", b"ignore_list_file", "ingress_id", b"ingress_id", "schema_format", b"schema_format", "white_list_file", b"white_list_file"]) -> None: ...

global___BaseImporterParameters = BaseImporterParameters

class PreprocessParameters(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    FILTER_DISCONNECTABLE_BRANCHES_PROCESSES_FIELD_NUMBER: builtins.int
    ACTION_SET_FILTER_BRIDGE_LOOKUP_FIELD_NUMBER: builtins.int
    ACTION_SET_FILTER_BSDF_LODF_FIELD_NUMBER: builtins.int
    ACTION_SET_FILTER_BSDF_LODF_BATCH_SIZE_FIELD_NUMBER: builtins.int
    ACTION_SET_CLIP_FIELD_NUMBER: builtins.int
    ASSET_TOPO_CLOSE_COUPLERS_FIELD_NUMBER: builtins.int
    REALISE_STATION_BUSBAR_CHOICE_HEURISTIC_FIELD_NUMBER: builtins.int
    AC_DC_INTERPOLATION_FIELD_NUMBER: builtins.int
    ENABLE_N_2_FIELD_NUMBER: builtins.int
    N_2_MORE_SPLITS_PENALTY_FIELD_NUMBER: builtins.int
    ENABLE_BB_OUTAGE_FIELD_NUMBER: builtins.int
    BB_OUTAGE_AS_NMINUS1_FIELD_NUMBER: builtins.int
    BB_OUTAGE_MORE_SPLITS_PENALTY_FIELD_NUMBER: builtins.int
    CLIP_BB_OUTAGE_PENALTY_FIELD_NUMBER: builtins.int
    DOUBLE_LIMIT_N0_FIELD_NUMBER: builtins.int
    DOUBLE_LIMIT_N1_FIELD_NUMBER: builtins.int
    INITIAL_LOADFLOW_PROCESSES_FIELD_NUMBER: builtins.int
    filter_disconnectable_branches_processes: builtins.int
    action_set_filter_bridge_lookup: builtins.bool
    action_set_filter_bsdf_lodf: builtins.bool
    action_set_filter_bsdf_lodf_batch_size: builtins.int
    action_set_clip: builtins.int
    asset_topo_close_couplers: builtins.bool
    realise_station_busbar_choice_heuristic: builtins.str
    ac_dc_interpolation: builtins.float
    enable_n_2: builtins.bool
    n_2_more_splits_penalty: builtins.float
    enable_bb_outage: builtins.bool
    bb_outage_as_nminus1: builtins.bool
    bb_outage_more_splits_penalty: builtins.float
    clip_bb_outage_penalty: builtins.bool
    double_limit_n0: builtins.float
    double_limit_n1: builtins.float
    initial_loadflow_processes: builtins.int
    def __init__(
        self,
        *,
        filter_disconnectable_branches_processes: builtins.int = ...,
        action_set_filter_bridge_lookup: builtins.bool = ...,
        action_set_filter_bsdf_lodf: builtins.bool = ...,
        action_set_filter_bsdf_lodf_batch_size: builtins.int = ...,
        action_set_clip: builtins.int = ...,
        asset_topo_close_couplers: builtins.bool = ...,
        realise_station_busbar_choice_heuristic: builtins.str = ...,
        ac_dc_interpolation: builtins.float = ...,
        enable_n_2: builtins.bool = ...,
        n_2_more_splits_penalty: builtins.float = ...,
        enable_bb_outage: builtins.bool = ...,
        bb_outage_as_nminus1: builtins.bool = ...,
        bb_outage_more_splits_penalty: builtins.float = ...,
        clip_bb_outage_penalty: builtins.bool = ...,
        double_limit_n0: builtins.float = ...,
        double_limit_n1: builtins.float = ...,
        initial_loadflow_processes: builtins.int = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["ac_dc_interpolation", b"ac_dc_interpolation", "action_set_clip", b"action_set_clip", "action_set_filter_bridge_lookup", b"action_set_filter_bridge_lookup", "action_set_filter_bsdf_lodf", b"action_set_filter_bsdf_lodf", "action_set_filter_bsdf_lodf_batch_size", b"action_set_filter_bsdf_lodf_batch_size", "asset_topo_close_couplers", b"asset_topo_close_couplers", "bb_outage_as_nminus1", b"bb_outage_as_nminus1", "bb_outage_more_splits_penalty", b"bb_outage_more_splits_penalty", "clip_bb_outage_penalty", b"clip_bb_outage_penalty", "double_limit_n0", b"double_limit_n0", "double_limit_n1", b"double_limit_n1", "enable_bb_outage", b"enable_bb_outage", "enable_n_2", b"enable_n_2", "filter_disconnectable_branches_processes", b"filter_disconnectable_branches_processes", "initial_loadflow_processes", b"initial_loadflow_processes", "n_2_more_splits_penalty", b"n_2_more_splits_penalty", "realise_station_busbar_choice_heuristic", b"realise_station_busbar_choice_heuristic"]) -> None: ...

global___PreprocessParameters = PreprocessParameters

class StartPreprocessingCommand(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    IMPORTER_PARAMETERS_FIELD_NUMBER: builtins.int
    PREPROCESS_PARAMETERS_FIELD_NUMBER: builtins.int
    PREPROCESS_ID_FIELD_NUMBER: builtins.int
    @property
    def importer_parameters(self) -> global___BaseImporterParameters: ...
    @property
    def preprocess_parameters(self) -> global___PreprocessParameters: ...
    preprocess_id: builtins.str
    def __init__(
        self,
        *,
        importer_parameters: global___BaseImporterParameters | None = ...,
        preprocess_parameters: global___PreprocessParameters | None = ...,
        preprocess_id: builtins.str = ...,
    ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["importer_parameters", b"importer_parameters", "preprocess_parameters", b"preprocess_parameters"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["importer_parameters", b"importer_parameters", "preprocess_id", b"preprocess_id", "preprocess_parameters", b"preprocess_parameters"]) -> None: ...

global___StartPreprocessingCommand = StartPreprocessingCommand

class ShutdownCommand(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    EXIT_CODE_FIELD_NUMBER: builtins.int
    exit_code: builtins.int
    def __init__(
        self,
        *,
        exit_code: builtins.int = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["exit_code", b"exit_code"]) -> None: ...

global___ShutdownCommand = ShutdownCommand

class Command(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    START_PREPROCESSING_FIELD_NUMBER: builtins.int
    SHUTDOWN_FIELD_NUMBER: builtins.int
    TIMESTAMP_FIELD_NUMBER: builtins.int
    UUID_FIELD_NUMBER: builtins.int
    @property
    def start_preprocessing(self) -> global___StartPreprocessingCommand: ...
    @property
    def shutdown(self) -> global___ShutdownCommand: ...
    @property
    def timestamp(self) -> google.protobuf.timestamp_pb2.Timestamp: ...
    uuid: builtins.str
    def __init__(
        self,
        *,
        start_preprocessing: global___StartPreprocessingCommand | None = ...,
        shutdown: global___ShutdownCommand | None = ...,
        timestamp: google.protobuf.timestamp_pb2.Timestamp | None = ...,
        uuid: builtins.str = ...,
    ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["command", b"command", "shutdown", b"shutdown", "start_preprocessing", b"start_preprocessing", "timestamp", b"timestamp"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["command", b"command", "shutdown", b"shutdown", "start_preprocessing", b"start_preprocessing", "timestamp", b"timestamp", "uuid", b"uuid"]) -> None: ...
    def WhichOneof(self, oneof_group: typing_extensions.Literal["command", b"command"]) -> typing_extensions.Literal["start_preprocessing", "shutdown"] | None: ...

global___Command = Command
