# Copyright 2026 50Hertz Transmission GmbH and Elia Transmission Belgium SA/NV
#
# This Source Code Form is subject to the terms of the Mozilla Public License, v. 2.0.
# If a copy of the MPL was not distributed with this file,
# you can obtain one at https://mozilla.org/MPL/2.0/.
# Mozilla Public License, version 2.0

"""Configuration for structured logging including OTEL compatibility.

The logging level is set to INFO by default, but can be configured.

Includes a singleton logger instance for the Interfaces package, which can be imported and used directly.
"""

import logging
import sys
import threading
import time
import traceback
from collections.abc import MutableMapping
from typing import Any, cast

import structlog

# Type alias matching structlog's EventDict
_EventDict = MutableMapping[str, Any]


# --- OTEL processor ---
class OtelLogProcessorFilter:
    """Extracts attributes from structlog and puts them into LogRecord attributes.

    Extracts both bound attributes from the logger and contextvars. Also
    deletes the log level (which is also added by OTEL) and the `_name` and
    `_logger` log record attributes that are added by `wrap_for_formatter`.

    **Important**: This is not a real logging filter, but a "processor" that mutates the
        log record in-place and always returns True to indicate that the log record should be emitted.
        This is necessary to get the event dict into the right shape for OTEL to pick up the structured
        log attributes, because OTEL logging handler does not expose a structlog-style processor chain API.

    Args:
        common_processors: The list of common processors to apply to foreign log records.
    """

    def __init__(
        self,
        common_processors: list[structlog.typing.Processor] | None = None,
    ) -> None:
        self._common_processors = common_processors or []

    def _apply_common_processors(self, record: logging.LogRecord, event_dict: _EventDict) -> _EventDict:
        """Apply the common processors to the event dict.

        This is useful for logs generated by the standard logging module,
        which do not go through the structlog processor chain.
        """
        logger_obj = logging.getLogger(record.name)
        method = record.levelname.lower()
        for processor in self._common_processors:
            event_dict = cast(_EventDict, processor(logger_obj, method, event_dict))
        return event_dict

    def filter(self, record: logging.LogRecord) -> bool:
        """Adjust the log record.

        Mutates the log record in-place and returns True to indicate that the record should be emitted.
        """
        event_dict: _EventDict = {}
        if isinstance(record.msg, dict):
            event_dict = record.msg
            # event_dict = structlog.contextvars.merge_contextvars(None, "", event_dict)
            # Remove duplicate information.
            event_dict.pop("level", None)
            delattr(record, "_name")
            delattr(record, "_logger")
            exc_info = event_dict.get("exc_info", False)
            if isinstance(exc_info, bool) and exc_info:
                record.exc_info = sys.exc_info()
        else:
            # Standard logging message or other, turn it into a string.
            event_dict["event"] = str(record.msg)
            event_dict = self._apply_common_processors(record, event_dict)

        event_dict.setdefault(
            "thread.name",
            getattr(record, "threadName", threading.current_thread().name),
        )

        new_message = event_dict.pop("event", event_dict.pop("msg", str(record.msg)))
        record.msg = new_message
        for key, value in event_dict.items():
            if not hasattr(record, key):
                setattr(record, key, value)
        return True


# --- processors ---


def _add_timestamp(_logger: Any, _method: str, event_dict: _EventDict) -> _EventDict:  # noqa: ANN401
    """Inject nanosecond Unix epoch timestamp."""
    event_dict["timestamp"] = time.time_ns()
    return event_dict


def _add_thread_name(_logger: Any, _method: str, event_dict: _EventDict) -> _EventDict:  # noqa: ANN401
    """Inject the current thread name."""
    event_dict.setdefault("thread.name", threading.current_thread().name)
    return event_dict


def _format_exception(_logger: Any, _method: str, event_dict: _EventDict) -> _EventDict:  # noqa: ANN401
    """Convert exc_info into OTel exception.* attributes."""
    exc_info = event_dict.pop("exc_info", None)
    if exc_info is None:
        return event_dict
    if exc_info is True:
        exc_info = sys.exc_info()
    elif isinstance(exc_info, BaseException):
        exc_info = (type(exc_info), exc_info, exc_info.__traceback__)
    exc_type, exc_value, exc_tb = exc_info
    if exc_type is not None and exc_value is not None:
        event_dict["exception.type"] = f"{exc_type.__module__}.{exc_type.__qualname__}"
        event_dict["exception.message"] = str(exc_value)
        event_dict["exception.stacktrace"] = "".join(traceback.format_exception(exc_type, exc_value, exc_tb))
    return event_dict


def _build_common_processors(
    custom_processors: list[structlog.types.Processor] | None = None,
) -> list[structlog.typing.Processor]:
    """Return the shared processor chain used by structlog and foreign log records.

    This is a convenience function to avoid duplicating the common processors in:

    - Structlog configuration
    - OTEL log filter for foreign log records
    - StreamHandler for foreign log records
    """
    common_processors: list[structlog.typing.Processor] = [
        structlog.processors.add_log_level,
        structlog.stdlib.add_logger_name,
        _add_timestamp,
        _add_thread_name,
        _format_exception,
        structlog.contextvars.merge_contextvars,
    ]
    if custom_processors:
        common_processors += custom_processors
    return common_processors


# --- configuration ---


def configure_structure_logging(
    log_level: int = logging.INFO,
    custom_processors: list[structlog.types.Processor] | None = None,
    show_locals_in_stacktrace: bool = False,
) -> None:
    """Configure structlog with the OTel processor chain. Idempotent.

    Find common log levels here: https://docs.python.org/3/library/logging.html#levels

    Implements structured logging for both structlog-based loggers and standard library loggers,
        with the same OTel-compatible output format.

    See https://www.structlog.org/en/stable/standard-library.html#rendering-using-structlog-based-formatters-within-logging
        for details.

    Args:
        log_level: The minimum log level to emit, as an int or valid level name string. Default is 20 (INFO).
        custom_processors: Optional list of additional structlog processors to include in the processing chain.
            These will be applied after the standard OTel processors.
        show_locals_in_stacktrace: If True, include local variables in the stack trace output when logging exceptions.
            Default is False to avoid sensitive information leakage.
            This only has an effect if the console renderer is used (i.e., when outputting to a TTY).
    """
    common_processors = _build_common_processors(custom_processors)

    # Configure structlog
    # This only affects structlog loggers.
    # The `wrap_for_formatter` processor stores the event dict into the log record for python logging handlers to process.

    structlog.configure(
        processors=[
            *common_processors,
            # Store event dict into log record for python logging handlers to process.
            structlog.stdlib.ProcessorFormatter.wrap_for_formatter,
        ],
        # Use standard library loggers, which is necessary for OTEL auto-instrumentation to pick up the logs.
        # That's where OTEL handler is attached by auto-instrumentation.
        logger_factory=structlog.stdlib.LoggerFactory(),
        # Cache loggers after first use for performance.
        # Logger is first instantiated on the first logging method call.
        cache_logger_on_first_use=True,
        context_class=dict,
        wrapper_class=structlog.make_filtering_bound_logger(log_level),
    )

    # Set up stream formatter to configure structlog machinery for output streams
    # This affects all loggers, including those that use the standard logging module directly.

    stream_processors = [
        # Remove metadata used to shuttle structlog events through logging.LogRecord.
        structlog.stdlib.ProcessorFormatter.remove_processors_meta,
    ]

    if sys.stdout.isatty():
        output = sys.stderr

        stream_processors += [
            # structlog itself uses several exception formatters. In case rich is installed,
            # 'RichTracebackFormatter' is a default option. By default 'RichTracebackFormatter' has
            # 'show_locals=True'. So to be safe, we can explicitly stick to 'rich' formatter and pass
            # 'show_locals' so we can be sure desired value is set.
            structlog.dev.ConsoleRenderer(
                exception_formatter=structlog.dev.RichTracebackFormatter(show_locals=show_locals_in_stacktrace)
            ),
        ]
    else:
        output = sys.stdout

        stream_processors += [
            # Keep in mind that this processor is used in deployed environments, and setting 'show_locals=True'
            # could lead to credentials being exposed in logs (e.g., in Loki) via stack traces.
            structlog.processors.ExceptionRenderer(
                structlog.tracebacks.ExceptionDictTransformer(
                    show_locals=False,
                )
            ),
            structlog.processors.JSONRenderer(),
        ]

    stream_formatter = structlog.stdlib.ProcessorFormatter(
        foreign_pre_chain=common_processors,  # Processors to run before `wrap_for_formatter`.
        processors=stream_processors,
    )

    # Configure handlers
    # - Otel handler, if OTEL auto-instrumentation is enabled
    # - Stream handler for human-readable output to console

    root_logger = logging.getLogger()

    for handler in list(root_logger.handlers):
        # Add the filter to OTEL logging handlers added by auto-instrumentation, if enabled.
        # This filter is responsible for extracting the event dict from structlog log records and
        # putting it into the log record attributes.
        # which is necessary for OTEL to pick up the structured log attributes.
        if handler.__class__.__module__.startswith("opentelemetry"):
            handler.addFilter(
                filter=OtelLogProcessorFilter(
                    common_processors=common_processors,
                )
            )
        # Remove all non OTEL handlers
        else:
            root_logger.removeHandler(handler)

    # Add Stream handler
    handler = logging.StreamHandler(stream=output)
    handler.setFormatter(stream_formatter)
    root_logger.addHandler(handler)
    root_logger.setLevel(log_level)


# Singleton logger instance for Interfaces package.
logger = structlog.get_logger("toop_engine_interfaces")
