"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
This is a temporary wrapper message for different message types so that we continue with our dev migration. 
This will be refactored later to be replaced by specific message definitions in the future.
"""

import builtins
import google.protobuf.descriptor
import google.protobuf.message
import sys
import typing

if sys.version_info >= (3, 10):
    import typing as typing_extensions
else:
    import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing.final
class MessageWrapper(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    MESSAGE_FIELD_NUMBER: builtins.int
    message: builtins.str
    """Wrapper for different message types
    Type of the message
    """
    def __init__(
        self,
        *,
        message: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["message", b"message"]) -> None: ...

Global___MessageWrapper: typing_extensions.TypeAlias = MessageWrapper
